import { Vault } from '../../vault/models/Vault';
import { resolveEntityName } from '../../shared/naming/AutoGeneratedName';
import { resolveFolderPathOrRoot } from '../../vault/persistence/resolveFolderPathOrRoot';

export interface ResolvedCreatePath {
  readonly path: string;
  readonly parentId: string | null;
}

/**
 * Computes a collision-free destination path for a newly created note.
 *
 * Pure with respect to the filesystem — it only reads the Vault's current
 * page/folder state, never touches disk. PageOperations.create() is the
 * only intended caller.
 *
 * Duplicate does not use this resolver (ADR-029): its destination name is
 * a provider decision (VaultFileSystem.duplicate()), never computed in
 * Application.
 */
export class PagePathResolver {
  constructor(private readonly vault: Vault) {}

  createNotePath(folderId: string | null, title: string): ResolvedCreatePath {
    const folderPath = resolveFolderPathOrRoot(this.vault, folderId);

    const candidateName = resolveEntityName(title, (name) =>
      this.vault.getPageByPath(`${folderPath}/${name}.md`) !== undefined
    );

    return {
      path: `${folderPath}/${candidateName}.md`,
      parentId: folderId,
    };
  }
}
