import { Vault } from '../../vault/models/Vault';
import { resolveEntityName } from '../../shared/naming/AutoGeneratedName';
import { resolveCollisionFreeName } from '../../shared/naming/resolveCollisionFreeName';
import { resolveFolderPathOrRoot } from '../../vault/persistence/resolveFolderPathOrRoot';
import { VaultPath } from '../../vault/ingest/VaultPath';

export interface ResolvedCreatePath {
  readonly path: string;
  readonly parentId: string | null;
}

/**
 * Computes a collision-free destination path for a newly created note.
 *
 * Pure with respect to the filesystem — it only reads the Vault's current
 * page/folder state, never touches disk. PageOperations.create() is the
 * only intended caller.
 */
export class PagePathResolver {
  constructor(private readonly vault: Vault) {}

  createNotePath(folderId: string | null, title: string): ResolvedCreatePath {
    const folderPath = resolveFolderPathOrRoot(this.vault, folderId);

    const candidateName = resolveEntityName(title, (name) =>
      this.vault.getPageByPath(`${folderPath}/${name}.md`) !== undefined
    );

    return {
      path: `${folderPath}/${candidateName}.md`,
      parentId: folderId,
    };
  }

  /**
   * Computes a collision-free destination path for duplicating an existing
   * note in place (same folder — PageOperations.duplicate() is the only
   * intended caller). Unlike createNotePath(), this never resolves a
   * parentId: Duplicate is a raw filesystem copy reconciled by
   * VaultSyncService, not a Gate `create`, so the destination's parentId
   * is resolved there, not here (see ADR-028).
   */
  duplicateNotePath(sourcePath: string): string {
    const folderPath = VaultPath.parentDirectory(sourcePath);
    const baseName = `${VaultPath.pageName(sourcePath)} copy`;

    const candidateName = resolveCollisionFreeName(
      baseName,
      (candidate) => this.vault.getPageByPath(`${folderPath}/${candidate}.md`) !== undefined
    );

    return `${folderPath}/${candidateName}.md`;
  }
}
