import { Vault } from '../../vault/models/Vault';
import { AUTO_GENERATED_NOTE_BASE_NAME } from '../../shared/naming/AutoGeneratedPageName';
import { resolveCollisionFreeName } from '../../shared/naming/resolveCollisionFreeName';
import { resolveFolderPathOrRoot } from '../../vault/persistence/resolveFolderPathOrRoot';

export interface ResolvedCreatePath {
  readonly path: string;
  readonly parentId: string | null;
}

/**
 * Computes a collision-free destination path for a newly created note.
 *
 * Pure with respect to the filesystem — it only reads the Vault's current
 * page/folder state, never touches disk. PageOperations.create() is the
 * only intended caller.
 */
export class PagePathResolver {
  constructor(private readonly vault: Vault) {}

  createNotePath(folderId: string | null, title: string): ResolvedCreatePath {
    const folderPath = resolveFolderPathOrRoot(this.vault, folderId);
    const baseName = title.trim() || AUTO_GENERATED_NOTE_BASE_NAME;

    const candidateName = resolveCollisionFreeName(baseName, (name) =>
      this.vault.getPageByPath(`${folderPath}/${name}.md`) !== undefined
    );

    return {
      path: `${folderPath}/${candidateName}.md`,
      parentId: folderId,
    };
  }
}
