import {
  ArrowCircleDownIcon,
  ArrowCircleRightIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowsInLineHorizontalIcon,
  ArrowsOutLineHorizontalIcon,
  ArrowUpIcon,
  BellIcon,
  BookIcon,
  CalendarBlankIcon,
  CalendarDotIcon,
  CalendarDotsIcon,
  CalendarIcon,
  CaretCircleRightIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChalkboardSimpleIcon,
  CheckCircleIcon,
  CheckSquareIcon,
  CheckSquareOffsetIcon,
  CircleIcon,
  ClockIcon,
  ColumnsIcon,
  DotIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  FlowArrowIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  GearIcon,
  KeyboardIcon,
  ListIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  MoonIcon,
  NoteBlankIcon,
  NoteIcon,
  NotePencilIcon,
  NotebookIcon,
  PlusIcon,
  QuestionIcon,
  SidebarSimpleIcon,
  SlidersHorizontalIcon,
  SmileyIcon,
  SmileyWinkIcon,
  SquareIcon,
  StarIcon,
  SunIcon,
  TableIcon,
  TabsIcon,
  TagIcon,
  TrashIcon,
  TrashSimpleIcon,
  TrayIcon,
  XIcon,
} from '@phosphor-icons/react';

// Centralized icon registry — never import directly from phosphor in feature code.
// Maps Figma “Icons” component variants (except Emojie) to Phosphor; filled/small variants
// share the same glyph — use `weight` / `size` on the component where needed.
//
// ICON_MEDIUM is the single source of truth for the default icon size.
// It is injected as --icon-medium CSS variable in main.tsx so both CSS and components stay in sync.
// To change the global icon size, update ICON_MEDIUM here only.
export const ICON_MEDIUM = 16;
export const Icons = {
  ArrowCircleDown: ArrowCircleDownIcon,
  ArrowCircleRight: ArrowCircleRightIcon,
  ArrowDown: ArrowDownIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowRight: ArrowRightIcon,
  ArrowSquareOut: ArrowSquareOutIcon,
  ArrowsInLineHorizontal: ArrowsInLineHorizontalIcon,
  ArrowsOutLineHorizontal: ArrowsOutLineHorizontalIcon,
  ArrowUp: ArrowUpIcon,
  Bell: BellIcon,
  Book: BookIcon,
  Calendar: CalendarIcon,
  CalendarBlank: CalendarBlankIcon,
  CalendarDot: CalendarDotIcon,
  CalendarDots: CalendarDotsIcon,
  CaretCircleRight: CaretCircleRightIcon,
  CaretDown: CaretDownIcon,
  /** Same glyph as CaretDown — use weight="fill" to match Figma “filled”. */
  CaretDownFilled: CaretDownIcon,
  CaretLeft: CaretLeftIcon,
  CaretRight: CaretRightIcon,
  /** Same glyph as CaretRight — use weight="fill" to match Figma “filled”. */
  CaretRightFilled: CaretRightIcon,
  CaretUp: CaretUpIcon,
  ChalkboardSimple: ChalkboardSimpleIcon,
  CheckCircle: CheckCircleIcon,
  /** Same glyph as CheckCircle — use weight="fill" for solid check. */
  CheckCircleFilled: CheckCircleIcon,
  CheckSquare: CheckSquareIcon,
  /** Same glyph as CheckSquare — use weight="fill" for filled square. */
  CheckSquareFill: CheckSquareIcon,
  CheckSquareOffset: CheckSquareOffsetIcon,
  Circle: CircleIcon,
  Clock: ClockIcon,
  Columns: ColumnsIcon,
  Dot: DotIcon,
  /** Horizontal ⋯ — alias for DotsThreeHorizontal. */
  DotsThree: DotsThreeIcon,
  DotsThreeHorizontal: DotsThreeIcon,
  DotsThreeVertical: DotsThreeVerticalIcon,
  FlowArrow: FlowArrowIcon,
  Folder: FolderIcon,
  FolderOpen: FolderOpenIcon,
  FolderPlus: FolderPlusIcon,
  Gear: GearIcon,
  Keyboard: KeyboardIcon,
  List: ListIcon,
  MagnifyingGlass: MagnifyingGlassIcon,
  Minus: MinusIcon,
  Moon: MoonIcon,
  Note: NoteIcon,
  NoteBlank: NoteBlankIcon,
  NotePencil: NotePencilIcon,
  Notebook: NotebookIcon,
  Plus: PlusIcon,
  Question: QuestionIcon,
  SidebarSimple: SidebarSimpleIcon,
  SlidersHorizontal: SlidersHorizontalIcon,
  Smiley: SmileyIcon,
  SmileyWink: SmileyWinkIcon,
  Square: SquareIcon,
  Star: StarIcon,
  /** Same glyph — use weight="fill". */
  StarFilled: StarIcon,
  /** Same glyph — use smaller size prop. */
  StarFilledSmall: StarIcon,
  /** Same glyph — use smaller size prop. */
  StarSmall: StarIcon,
  Sun: SunIcon,
  Table: TableIcon,
  Tabs: TabsIcon,
  Tag: TagIcon,
  Trash: TrashIcon,
  TrashSimple: TrashSimpleIcon,
  Tray: TrayIcon,
  X: XIcon,
};
