import type { Folder } from '@core/vault/models';
import type { Vault } from '@core/vault/models/Vault';
import type { VaultQuery } from '@core/vault/queries/VaultQuery';
import type { FilteredView, Workspace } from '@core/workspace/Workspace';
import type { EffectivePage, EffectivePageState } from '@core/application/page/EffectivePageState';
import type { MembershipSelector } from '@core/application/membership/MembershipSelector';
import { buildEntryPresentation } from '@core/presentation/buildEntryPresentation';
import { getTagLineContexts } from '@core/presentation/getTagLineContexts';
import { normalizeTagName } from '@core/vault/models/Tag';
import { getVaultDisplayName } from '@core/presentation/getVaultDisplayName';
import { isAutoGeneratedName } from '@core/shared/naming/AutoGeneratedName';
import {
  getSystemLocationForFolder,
  getSystemLocationPresentation,
} from '@core/presentation/systemPresentation';

import type { CollectionEntryModel, CollectionEntryValues } from './CollectionEntryModel';
import type {
  CollectionPageActions,
  CollectionPageModel,
} from './CollectionPageModel';

/**
 * What toCollectionPageModel builds a page from: either a real Folder's
 * children, or a filtered view (ADR-022) — Workspace-root, Favorites, or a
 * tag — none of which is one folder's children. Discriminated by `view`
 * rather than `type`, since neither Folder nor EffectivePage has a `view`
 * field, mirroring isFolder()'s own Folder/EffectivePage discrimination.
 */
export type CollectionPageSource = Folder | { readonly view: FilteredView };

function isFolder(entry: Folder | EffectivePage): entry is Folder {
  return !('type' in entry);
}

/**
 * A folder's collection property values: its name, its type — and, once it has been archived, the date it
 * was (`FolderMetadata.archivedAt`, null everywhere but the Archive). A folder has no created or
 * last-edited dates, and nothing in a collection shows its description or cover.
 */
export function toFolderValues(name: string, folder: Folder): CollectionEntryValues {
  return { name, type: 'Folder', ...(folder.metadata.archivedAt && { archived: folder.metadata.archivedAt }) };
}

/**
 * A note's collection property values, from its `EffectivePage` — the one place that knows
 * where each comes from (the page's own frontmatter timestamps, its description, its cover).
 * A value the note does not have is left out; a HIDDEN cover is no cover (it is shown nowhere
 * in the collection, and does not count when sorting by Cover image).
 */
export function toNoteValues(name: string, page: EffectivePage): CollectionEntryValues {
  return {
    name,
    type: 'Note',
    ...(page.description != null && { description: page.description }),
    ...(page.cover && !page.coverHidden && { cover: page.cover }),
    ...(page.createdAt && { created: page.createdAt }),
    ...(page.updatedAt && { updated: page.updatedAt }),
    ...(page.archivedAt && { archived: page.archivedAt }),
  };
}

/**
 * Maps a Folder or EffectivePage to a CollectionEntryModel for collection
 * listing. Pages come from EffectivePageState (ARCHITECTURE_RULES.md rule
 * 13) — existence, label, and icon for both durable and draft-only pages,
 * the same read façade FolderTree/DailyNotesList already use. Draft
 * accumulation is prevented at creation time (PageOperations's
 * findReusableDraftId), not by filtering here.
 *
 * The entry's collection property values (`values`) are raw: a note gets them from its
 * `EffectivePage` (`toNoteValues`); a folder carries only its name — `FolderMetadata`
 * has no created/updated equivalent, and nothing in the collection shows a folder's
 * description or cover today. `subfolderCount`/`noteCount` are folder-only payload, not
 * properties — from the same `membershipSelector` queries `toFolderCollectionPageModel`
 * already uses for that folder's own listing, called one level down (the folder's
 * children, not the folder itself).
 */
function toCollectionEntry(
  entry: Folder | EffectivePage,
  actions: CollectionPageActions,
  selected: boolean,
  membershipSelector: MembershipSelector,
  /** Set only when building entries for a Tag collection view (`toFilteredCollectionPageModel`'s `view.kind === 'tag'` branch) — see `CollectionPageActions.onOpenNote`'s own doc comment. */
  revealTagName?: string,
  /**
   * Tag collection only: for a matching-content entry, the one body line it stands for (`tagLine`, with its `index`
   * among the note's lines making the entry id unique).
   */
  tagEntry?: { readonly line?: { readonly text: string; readonly index: number } }
): CollectionEntryModel {
  const type = isFolder(entry) ? 'folder' : 'note';
  const { title, icon, emoji } = buildEntryPresentation(entry);
  // An active folder counts what the active app shows inside it; an archived one (a row in the Archive)
  // counts what it physically holds, since the active views return nothing for an archived parent.
  const folderCounts = isFolder(entry)
    ? membershipSelector.isEffectivelyArchived(entry.id)
      ? membershipSelector.countChildren(entry.id)
      : {
          subfolders: membershipSelector.getVisibleChildFolders(entry.id).length,
          notes: membershipSelector.getVisibleChildPages(entry.id).length,
        }
    : undefined;

  const tagLine = isFolder(entry) ? undefined : tagEntry?.line;
  const noteValues = isFolder(entry) ? toFolderValues(title, entry) : toNoteValues(title, entry);

  return {
    // A matching-content entry has an id of its own (several per note); `noteId` keeps the note's.
    id: tagLine ? `${entry.id}#tag-line-${tagLine.index}` : entry.id,
    noteId: tagLine ? entry.id : undefined,
    type,
    icon,
    emoji,
    selected,
    // Its Name is the line itself, so sorting by name sorts what the entry shows; its Source is the note the line lives
    // in (the note's display label, as the Tags sidebar's note row shows it); every other value is the note's.
    values: tagLine ? { ...noteValues, name: tagLine.text, source: title } : noteValues,
    markdown: isFolder(entry) ? undefined : entry.markdown,
    coverPositionAbove: isFolder(entry) ? undefined : entry.coverPositionAbove,
    tagLine: tagLine?.text,
    subfolderCount: isFolder(entry) ? folderCounts?.subfolders : undefined,
    noteCount: isFolder(entry) ? folderCounts?.notes : undefined,
    onClick: () => {
      if (isFolder(entry)) {
        actions.onOpenFolder(entry.id);
        return;
      }

      if (entry.isDraft) {
        actions.onOpenDraftNote(entry.id);
        return;
      }

      actions.onOpenNote(entry.id, revealTagName);
    },
  };
}

/**
 * The notes the "From template" picker offers: every visible page in the
 * reserved Templates folder or anywhere beneath it — the folder is the source
 * of truth for what is a template (ADR-041), so this reads it through the same
 * MembershipSelector queries a folder's own collection page does, no second
 * discovery mechanism. A template that was never created (the folder is lazy,
 * ADR-030) simply yields none.
 *
 * Each entry is the ordinary note entry (so the picker lists the same
 * notes a collection does), except that choosing it does not open the
 * template: `onUse` receives the template's body Markdown instead.
 */
export function toTemplateEntries(
  vault: Vault,
  membershipSelector: MembershipSelector,
  onUse: (markdown: string) => void
): CollectionEntryModel[] {
  const root = vault.getReservedFolder('templates');

  if (!root) {
    return [];
  }

  const entries: CollectionEntryModel[] = [];
  const unreachable = (): void => undefined;
  const collect = (folderId: string): void => {
    for (const page of membershipSelector.getVisibleChildPages(folderId)) {
      const entry = toCollectionEntry(
        page,
        {
          onOpenFolder: unreachable,
          onOpenNote: () => onUse(page.markdown),
          onOpenDraftNote: () => onUse(page.markdown),
        },
        false,
        membershipSelector
      );

      entries.push({ ...entry, onClick: () => onUse(page.markdown) });
    }

    for (const folder of membershipSelector.getVisibleChildFolders(folderId)) {
      collect(folder.id);
    }
  };

  collect(root.id);

  return entries;
}

function isFolderSource(source: CollectionPageSource): source is Folder {
  return !('view' in source);
}

/**
 * A Workspace-root, Favorites, or single-tag collection page (ADR-022).
 * Workspace-folder membership comes from MembershipSelector.getWorkspaceFolders()
 * (ADR-023) — the same call the sidebar's FolderTree makes at its root, so
 * the page can never drift from what the sidebar shows for the same view
 * (this was previously two independent calls — query.getRootFolders() here,
 * unfiltered, vs. query.getVisibleRootFolders() in FolderTree — see
 * ADR-023's Context section). Favorites/tag membership are unaffected —
 * getFavoriteFolders()/getFavoritePages()/getPagesByTag() remain
 * VaultQuery/EffectivePageState's structural/durable-only jobs, per
 * ARCHITECTURE_RULES.md rule 13's documented exception; neither is a
 * membership question MembershipSelector owns.
 *
 * The tag branch returns early: a tag has no folders (folders: [] always)
 * and its title/icon come from the Tag entity itself (vault.getTagByName),
 * never from the system-location presentation table below, which has no
 * per-tag entries and structurally can't (it's a closed, fixed-key
 * lookup — see the investigation this followed).
 */
function toFilteredCollectionPageModel(
  view: FilteredView,
  vault: Vault,
  query: VaultQuery,
  effectivePageState: EffectivePageState,
  membershipSelector: MembershipSelector,
  workspace: Workspace,
  actions: CollectionPageActions
): CollectionPageModel {
  if (view.kind === 'tag') {
    const tag = vault.getTagByName(view.tagName);
    const tagKey = normalizeTagName(view.tagName);
    // The Tags sidebar's own expansion of a tag (renderTags.getTagChildren), as collection entries: per note, a note
    // entry when it belongs through frontmatter (or is a draft), then one entry per distinct line that contains the tag
    // (`getTagLineContexts` — two occurrences on one line are one line there, so one entry here). Notes with an inline
    // occurrence come first, then the frontmatter-only ones, each in the tag index's own order; no new sort.
    const children = effectivePageState.getPagesByTag(view.tagName).map((child) => {
      const page = vault.getPage(child.id);
      const lines = getTagLineContexts(page, view.tagName).map((context) => context.lineText);

      return {
        child,
        lines,
        // A draft carries the tag as note-level membership, like a frontmatter entry.
        hasFrontmatterMembership:
          child.isDraft || (page?.metadata.tags ?? []).some((name) => normalizeTagName(name) === tagKey),
      };
    });
    const notes = [
      ...children.filter(({ lines }) => lines.length > 0),
      ...children.filter(({ lines }) => lines.length === 0),
    ].flatMap(({ child, lines, hasFrontmatterMembership }) => {
      const selected = workspace.activePageId === child.id;
      const entryFor = (line?: { text: string; index: number }) =>
        toCollectionEntry(child, actions, selected, membershipSelector, view.tagName, { line });

      return [
        // A note with no line to show is still listed once (a frontmatter-only note, or a draft).
        ...(hasFrontmatterMembership || lines.length === 0 ? [entryFor()] : []),
        ...lines.map((text, index) => entryFor({ text, index })),
      ];
    });

    return {
      title: tag?.name ?? view.tagName,
      description: '',
      coverImage: null,
      coverHidden: false,
      coverLayout: 'side',
      coverPositionAbove: 50,
      coverPositionSide: 50,
      folders: [],
      notes,
    };
  }

  const rawFolders =
    view.kind === 'workspace'
      ? membershipSelector.getWorkspaceFolders()
      : query.getFavoriteFolders();
  // ADR-023: narrowed to Notes membership for the same reason FolderTree's
  // root-level page list is (Sidebar.Notes.tsx §FolderTree) — Workspace's
  // page list and the sidebar's "Workspace" section render the same root
  // page set, so a root-level Daily Note draft (folderId: null, before its
  // month folder exists) must be excluded from both surfaces identically,
  // not just the sidebar one.
  const rawNotes =
    view.kind === 'workspace'
      ? membershipSelector.getNotesChildPages(null)
      : effectivePageState.getFavoritePages();

  // Workspace-root is the one filtered view that IS the vault root itself
  // (ADR-022's own "Why Workspace/Favorites are views, not folders" section:
  // Workspace-root is exactly `parentId === null`, i.e. the root). Its title
  // is therefore the vault's own physical folder name (getVaultDisplayName),
  // the same exception the sidebar's root section header already makes
  // (Sidebar.Notes.tsx) — ADR-022 Amendment 2. Favorites has no such
  // identity (it's a cross-cutting filter, not a location) and keeps the
  // generic systemPresentation label.
  const title =
    view.kind === 'workspace'
      ? getVaultDisplayName(vault.root)
      : getSystemLocationPresentation(view.kind).label;

  return {
    title,
    description: '',
    coverImage: null,
    coverHidden: false,
    coverLayout: 'side',
    coverPositionAbove: 50,
    coverPositionSide: 50,
    folders: rawFolders.map((child) =>
      toCollectionEntry(child, actions, workspace.activeFolderId === child.id, membershipSelector)
    ),
    notes: rawNotes.map((child) =>
      toCollectionEntry(child, actions, workspace.activePageId === child.id, membershipSelector)
    ),
  };
}

function toFolderCollectionPageModel(
  folder: Folder,
  membershipSelector: MembershipSelector,
  workspace: Workspace,
  actions: CollectionPageActions
): CollectionPageModel {
  // Dot-prefixed names are hidden from the UI at every depth (not just
  // Workspace root) — MembershipSelector's getVisibleChildFolders/
  // getVisibleChildPages apply that one presentation filter without
  // narrowing by page type, since a folder's own Collection page shows
  // every child it has, not just Notes.
  // An archived folder's own page shows its real contents (the active views return nothing for an
  // archived parent), read-only; every other folder lists what the active app shows inside it.
  const archivedContents = membershipSelector.isEffectivelyArchived(folder.id)
    ? membershipSelector.getArchivedFolderContents(folder.id)
    : undefined;

  const folders = (archivedContents?.folders ?? membershipSelector.getVisibleChildFolders(folder.id)).map(
    (child) =>
      toCollectionEntry(child, actions, workspace.activeFolderId === child.id, membershipSelector)
  );

  const notes = (archivedContents?.pages ?? membershipSelector.getVisibleChildPages(folder.id))
    .map((child) =>
      toCollectionEntry(child, actions, workspace.activePageId === child.id, membershipSelector)
    );

  // A reserved folder (Archive, Inbox, Templates, Daily Notes) viewed
  // directly gets its canonical system-location label instead of the raw
  // Vault folder name — same helper buildBreadcrumbs' ancestor handling
  // uses, so the two surfaces can't drift.
  //
  // This title feeds Page's editable header (Category B, an identity/
  // editing surface — PageHost passes it straight to <Page title={...}>),
  // not a browse-only display label — so an ordinary untitled folder gets
  // the same treatment toResourcePageModel gives an untitled Note's
  // header: empty, not the literal placeholder text, so Page's own
  // titlePlaceholder/EditableText placeholder mechanism renders it and the
  // field autofocuses exactly like a fresh untitled Note's does.
  // getFolderDisplayLabel (text-or-placeholder, no styling channel out of
  // this model) is the browse-surface function for folder *rows* (sidebar,
  // Collection body entries via buildEntryPresentation) — deliberately not
  // used here.
  const systemLocation = getSystemLocationForFolder(folder, membershipSelector);
  const title = systemLocation
    ? getSystemLocationPresentation(systemLocation).label
    : isAutoGeneratedName(folder.name)
      ? ''
      : folder.name;

  return {
    title,
    description: folder.metadata.description ?? '',
    coverImage: folder.metadata.cover,
    coverHidden: folder.metadata.coverHidden,
    coverLayout: folder.metadata.coverLayout,
    coverPositionAbove: folder.metadata.coverPositionAbove,
    coverPositionSide: folder.metadata.coverPositionSide,
    folders,
    notes,
  };
}

export function toCollectionPageModel(
  source: CollectionPageSource,
  vault: Vault,
  query: VaultQuery,
  effectivePageState: EffectivePageState,
  membershipSelector: MembershipSelector,
  workspace: Workspace,
  actions: CollectionPageActions
): CollectionPageModel {
  if (isFolderSource(source)) {
    return toFolderCollectionPageModel(source, membershipSelector, workspace, actions);
  }

  return toFilteredCollectionPageModel(
    source.view,
    vault,
    query,
    effectivePageState,
    membershipSelector,
    workspace,
    actions
  );
}
