import type { Folder } from '@core/vault/models';
import type { Vault } from '@core/vault/models/Vault';
import type { VaultQuery } from '@core/vault/queries/VaultQuery';
import type { FilteredView, Workspace } from '@core/workspace/Workspace';
import type { EffectivePage, EffectivePageState } from '@core/application/page/EffectivePageState';
import type { MembershipSelector } from '@core/application/membership/MembershipSelector';
import { buildEntryPresentation } from '@core/presentation/buildEntryPresentation';
import { getVaultDisplayName } from '@core/presentation/getVaultDisplayName';
import { isAutoGeneratedName } from '@core/shared/naming/AutoGeneratedName';
import { formatRelativeTimestamp } from '@shared/helpers/time/dateDisplay';
import {
  getSystemLocationForFolder,
  getSystemLocationPresentation,
} from '@core/presentation/systemPresentation';

import type { CollectionEntryModel } from './CollectionEntryModel';
import type {
  CollectionPageActions,
  CollectionPageModel,
} from './CollectionPageModel';

/**
 * What toCollectionPageModel builds a page from: either a real Folder's
 * children, or a filtered view (ADR-022) — Workspace-root, Favorites, or a
 * tag — none of which is one folder's children. Discriminated by `view`
 * rather than `type`, since neither Folder nor EffectivePage has a `view`
 * field, mirroring isFolder()'s own Folder/EffectivePage discrimination.
 */
export type CollectionPageSource = Folder | { readonly view: FilteredView };

function isFolder(entry: Folder | EffectivePage): entry is Folder {
  return !('type' in entry);
}

/**
 * Formats a persisted `PageMetadata` timestamp (a full ISO instant, e.g.
 * `2026-07-08T14:03:00.000Z`) for the collection Table/List views' display
 * columns — `formatRelativeTimestamp`'s local-time `35 minutes ago` (under two hours) /
 * `Today, 09:03 AM` / `Yesterday, 09:03 AM` / `12 Aug, 09:03 AM` shape. `null` (never persisted, or a pre-promotion
 * draft — see EffectivePage's own doc comment) renders as nothing.
 */
export function formatEntryTimestamp(isoTimestamp: string | null): string | undefined {
  if (!isoTimestamp) return undefined;
  const parsed = new Date(isoTimestamp);
  return Number.isNaN(parsed.getTime()) ? undefined : formatRelativeTimestamp(parsed);
}

/**
 * Maps a Folder or EffectivePage to a CollectionEntryModel for collection
 * listing. Pages come from EffectivePageState (ARCHITECTURE_RULES.md rule
 * 13) — existence, label, and icon for both durable and draft-only pages,
 * the same read façade FolderTree/DailyNotesList already use. Draft
 * accumulation is prevented at creation time (PageOperations's
 * findReusableDraftId), not by filtering here.
 *
 * `created`/`updated` are the Table/List-view display fields
 * (collection-view wiring) — a note entry gets them from its own
 * `EffectivePage` timestamps. `FolderMetadata` has no created/updated
 * equivalent, so a folder entry leaves both undefined — not a wiring gap,
 * a genuinely missing field. `subfolderCount`/`noteCount` are the reverse
 * — only ever set for a folder entry, from the same `membershipSelector`
 * queries `toFolderCollectionPageModel` already uses for that folder's own
 * listing, called one level down (the folder's children, not the folder
 * itself).
 */
function toCollectionEntry(
  entry: Folder | EffectivePage,
  actions: CollectionPageActions,
  selected: boolean,
  membershipSelector: MembershipSelector,
  /** Set only when building entries for a Tag collection view (`toFilteredCollectionPageModel`'s `view.kind === 'tag'` branch) — see `CollectionPageActions.onOpenNote`'s own doc comment. */
  revealTagName?: string
): CollectionEntryModel {
  const type = isFolder(entry) ? 'folder' : 'note';
  const { title, icon, emoji } = buildEntryPresentation(entry);

  return {
    id: entry.id,
    type,
    title,
    icon,
    emoji,
    selected,
    created: isFolder(entry) ? undefined : formatEntryTimestamp(entry.createdAt),
    updated: isFolder(entry) ? undefined : formatEntryTimestamp(entry.updatedAt),
    createdAt: isFolder(entry) ? undefined : (entry.createdAt ?? undefined),
    updatedAt: isFolder(entry) ? undefined : (entry.updatedAt ?? undefined),
    archived: isFolder(entry) ? undefined : formatEntryTimestamp(entry.archivedAt),
    archivedAt: isFolder(entry) ? undefined : (entry.archivedAt ?? undefined),
    description: isFolder(entry) ? undefined : (entry.description ?? undefined),
    markdown: isFolder(entry) ? undefined : entry.markdown,
    cover: isFolder(entry) ? undefined : (entry.cover ?? undefined),
    coverHidden: isFolder(entry) ? undefined : entry.coverHidden,
    coverPositionAbove: isFolder(entry) ? undefined : entry.coverPositionAbove,
    subfolderCount: isFolder(entry)
      ? membershipSelector.getVisibleChildFolders(entry.id).length
      : undefined,
    noteCount: isFolder(entry)
      ? membershipSelector.getVisibleChildPages(entry.id).length
      : undefined,
    onClick: () => {
      if (isFolder(entry)) {
        actions.onOpenFolder(entry.id);
        return;
      }

      if (entry.isDraft) {
        actions.onOpenDraftNote(entry.id);
        return;
      }

      actions.onOpenNote(entry.id, revealTagName);
    },
  };
}

function isFolderSource(source: CollectionPageSource): source is Folder {
  return !('view' in source);
}

/**
 * A Workspace-root, Favorites, or single-tag collection page (ADR-022).
 * Workspace-folder membership comes from MembershipSelector.getWorkspaceFolders()
 * (ADR-023) — the same call the sidebar's FolderTree makes at its root, so
 * the page can never drift from what the sidebar shows for the same view
 * (this was previously two independent calls — query.getRootFolders() here,
 * unfiltered, vs. query.getVisibleRootFolders() in FolderTree — see
 * ADR-023's Context section). Favorites/tag membership are unaffected —
 * getFavoriteFolders()/getFavoritePages()/getPagesByTag() remain
 * VaultQuery/EffectivePageState's structural/durable-only jobs, per
 * ARCHITECTURE_RULES.md rule 13's documented exception; neither is a
 * membership question MembershipSelector owns.
 *
 * The tag branch returns early: a tag has no folders (folders: [] always)
 * and its title/icon come from the Tag entity itself (vault.getTagByName),
 * never from the system-location presentation table below, which has no
 * per-tag entries and structurally can't (it's a closed, fixed-key
 * lookup — see the investigation this followed).
 */
function toFilteredCollectionPageModel(
  view: FilteredView,
  vault: Vault,
  query: VaultQuery,
  effectivePageState: EffectivePageState,
  membershipSelector: MembershipSelector,
  workspace: Workspace,
  actions: CollectionPageActions
): CollectionPageModel {
  if (view.kind === 'tag') {
    const tag = vault.getTagByName(view.tagName);
    const notes = effectivePageState
      .getPagesByTag(view.tagName)
      .map((child) =>
        toCollectionEntry(child, actions, workspace.activePageId === child.id, membershipSelector, view.tagName)
      );

    return {
      title: tag?.name ?? view.tagName,
      description: '',
      coverImage: null,
      coverHidden: false,
      coverLayout: 'side',
      coverPositionAbove: 50,
      coverPositionSide: 50,
      folders: [],
      notes,
    };
  }

  const rawFolders =
    view.kind === 'workspace'
      ? membershipSelector.getWorkspaceFolders()
      : query.getFavoriteFolders();
  // ADR-023: narrowed to Notes membership for the same reason FolderTree's
  // root-level page list is (Sidebar.Notes.tsx §FolderTree) — Workspace's
  // page list and the sidebar's "Workspace" section render the same root
  // page set, so a root-level Daily Note draft (folderId: null, before its
  // month folder exists) must be excluded from both surfaces identically,
  // not just the sidebar one.
  const rawNotes =
    view.kind === 'workspace'
      ? membershipSelector.getNotesChildPages(null)
      : effectivePageState.getFavoritePages();

  // Workspace-root is the one filtered view that IS the vault root itself
  // (ADR-022's own "Why Workspace/Favorites are views, not folders" section:
  // Workspace-root is exactly `parentId === null`, i.e. the root). Its title
  // is therefore the vault's own physical folder name (getVaultDisplayName),
  // the same exception the sidebar's root section header already makes
  // (Sidebar.Notes.tsx) — ADR-022 Amendment 2. Favorites has no such
  // identity (it's a cross-cutting filter, not a location) and keeps the
  // generic systemPresentation label.
  const title =
    view.kind === 'workspace'
      ? getVaultDisplayName(vault.root)
      : getSystemLocationPresentation(view.kind).label;

  return {
    title,
    description: '',
    coverImage: null,
    coverHidden: false,
    coverLayout: 'side',
    coverPositionAbove: 50,
    coverPositionSide: 50,
    folders: rawFolders.map((child) =>
      toCollectionEntry(child, actions, workspace.activeFolderId === child.id, membershipSelector)
    ),
    notes: rawNotes.map((child) =>
      toCollectionEntry(child, actions, workspace.activePageId === child.id, membershipSelector)
    ),
  };
}

function toFolderCollectionPageModel(
  folder: Folder,
  membershipSelector: MembershipSelector,
  workspace: Workspace,
  actions: CollectionPageActions
): CollectionPageModel {
  // Dot-prefixed names are hidden from the UI at every depth (not just
  // Workspace root) — MembershipSelector's getVisibleChildFolders/
  // getVisibleChildPages apply that one presentation filter without
  // narrowing by page type, since a folder's own Collection page shows
  // every child it has, not just Notes.
  const folders = membershipSelector
    .getVisibleChildFolders(folder.id)
    .map((child) =>
      toCollectionEntry(child, actions, workspace.activeFolderId === child.id, membershipSelector)
    );

  const notes = membershipSelector
    .getVisibleChildPages(folder.id)
    .map((child) =>
      toCollectionEntry(child, actions, workspace.activePageId === child.id, membershipSelector)
    );

  // A reserved folder (Archive, Templates, Daily Notes) viewed
  // directly gets its canonical system-location label instead of the raw
  // Vault folder name — same helper buildBreadcrumbs' ancestor handling
  // uses, so the two surfaces can't drift.
  //
  // This title feeds Page's editable header (Category B, an identity/
  // editing surface — PageHost passes it straight to <Page title={...}>),
  // not a browse-only display label — so an ordinary untitled folder gets
  // the same treatment toResourcePageModel gives an untitled Note's
  // header: empty, not the literal placeholder text, so Page's own
  // titlePlaceholder/EditableText placeholder mechanism renders it and the
  // field autofocuses exactly like a fresh untitled Note's does.
  // getFolderDisplayLabel (text-or-placeholder, no styling channel out of
  // this model) is the browse-surface function for folder *rows* (sidebar,
  // Collection body entries via buildEntryPresentation) — deliberately not
  // used here.
  const systemLocation = getSystemLocationForFolder(folder, membershipSelector);
  const title = systemLocation
    ? getSystemLocationPresentation(systemLocation).label
    : isAutoGeneratedName(folder.name)
      ? ''
      : folder.name;

  return {
    title,
    description: folder.metadata.description ?? '',
    coverImage: folder.metadata.cover,
    coverHidden: folder.metadata.coverHidden,
    coverLayout: folder.metadata.coverLayout,
    coverPositionAbove: folder.metadata.coverPositionAbove,
    coverPositionSide: folder.metadata.coverPositionSide,
    folders,
    notes,
  };
}

export function toCollectionPageModel(
  source: CollectionPageSource,
  vault: Vault,
  query: VaultQuery,
  effectivePageState: EffectivePageState,
  membershipSelector: MembershipSelector,
  workspace: Workspace,
  actions: CollectionPageActions
): CollectionPageModel {
  if (isFolderSource(source)) {
    return toFolderCollectionPageModel(source, membershipSelector, workspace, actions);
  }

  return toFilteredCollectionPageModel(
    source.view,
    vault,
    query,
    effectivePageState,
    membershipSelector,
    workspace,
    actions
  );
}
