import type { Page } from '../vault/models/Page';
import { isAutoGeneratedNoteName } from '../shared/naming/AutoGeneratedPageName';
import { getPrimaryDisplayText } from './getPrimaryDisplayText';
import { getPageTitlePlaceholder } from './PageDisplayPlaceholders';

export type PageDisplayLabelSource = 'title' | 'description' | 'content' | 'placeholder';

export interface PageDisplayLabel {
  readonly text: string;
  readonly source: PageDisplayLabelSource;
}

/**
 * The single, shared presentation rule for what to show as a page's label
 * — the one owner every rendering surface (sidebar, page header, and
 * eventually search/backlinks/references/recent notes) calls instead of
 * reading page.name directly or re-deriving its own fallback logic.
 *
 * Priority, shared by Notes and Daily Notes rather than two separate
 * systems: explicit filename -> description -> primary body content ->
 * placeholder. The only type-aware step is what counts as "the filename
 * is meaningful": a Note's filename can be a deliberate user choice, so
 * it's checked against isAutoGeneratedNoteName; a Daily Note's filename
 * is always a deterministic date, never chosen, so it never qualifies —
 * that's what keeps the date out of the label without a second chain.
 *
 * Presentation-only: never persisted, never touches Vault, and must never
 * be used for search matching, wiki-link resolution, or indexing, all of
 * which continue to resolve against the real page.name.
 */
export function getPageDisplayLabel(page: Page): PageDisplayLabel {
  if (page.type !== 'daily-note' && !isAutoGeneratedNoteName(page.name)) {
    return { text: page.name, source: 'title' };
  }

  const description = page.metadata.description?.trim();

  if (description) {
    return { text: description, source: 'description' };
  }

  const content = getPrimaryDisplayText(page.source.markdown);

  if (content) {
    return { text: content, source: 'content' };
  }

  return {
    text: getPageTitlePlaceholder(page.type),
    source: 'placeholder',
  };
}

/**
 * The single owner of "which title styling does a label get." Semantic,
 * not literal, and the rule differs by type — deliberately, not as two
 * unrelated special cases:
 *
 * - The literal placeholder fallback (source === 'placeholder' — "New
 *   Note" / "Daily Note") always renders as 'placeholder' for both types:
 *   it means "nothing was available at all," which is never a stand-in
 *   for real content.
 * - For Notes, everything short of the explicit title (description,
 *   content) is Clutter inferring a label to help identify an otherwise
 *   unnamed page, so it renders as 'placeholder' too — only source ===
 *   'title' is 'default'.
 * - For Daily Notes, a description or body content is real, deliberate
 *   information the user wrote — not a stand-in for a missing title the
 *   date could have been, since the date is never shown here at all
 *   (already represented elsewhere: day badge, month grouping, page
 *   header). So description/content render as 'default' for Daily Notes,
 *   even though the identical sources are 'placeholder' for Notes.
 *
 * Every rendering surface that shows a PageDisplayLabel calls this
 * instead of comparing label.source itself, so the distinction can't
 * drift between call sites or between the two page types.
 */
export function getPageDisplayLabelStyle(
  page: Page,
  label: PageDisplayLabel
): 'default' | 'placeholder' {
  if (label.source === 'placeholder') {
    return 'placeholder';
  }

  if (page.type === 'daily-note') {
    return 'default';
  }

  return label.source === 'title' ? 'default' : 'placeholder';
}
