import type { Page, PageType } from '../vault/models/Page';
import { isAutoGeneratedName } from '../shared/naming/AutoGeneratedName';
import { getPrimaryDisplayText } from './getPrimaryDisplayText';
import { getPageTitlePlaceholder } from './PageDisplayPlaceholders';

export type PageDisplayLabelSource = 'title' | 'description' | 'content' | 'placeholder';

export interface PageDisplayLabel {
  readonly text: string;
  readonly source: PageDisplayLabelSource;
}

/**
 * The minimal structural shape getPageDisplayLabel's precedence chain
 * actually reads — satisfied directly by EffectivePage (ADR-020's M3
 * amendment) and, via toPageDisplayLabelInput() below, by a Vault Page.
 * Loosened from a concrete Page so both can call this function without
 * either becoming the other's shape; the label logic itself is unchanged.
 */
export interface PageDisplayLabelInput {
  readonly type: PageType;
  readonly name: string;
  readonly description: string | null;
  readonly markdown: string;
}

/**
 * Adapts a Vault Page to the minimal shape getPageDisplayLabel needs —
 * the one place that translates Page's nested metadata/source shape into
 * the flat input the label rule reads, so no call site duplicates this
 * extraction (implementation-rules.md rule 4).
 */
export function toPageDisplayLabelInput(page: Page): PageDisplayLabelInput {
  return {
    type: page.type,
    name: page.name,
    description: page.metadata.description,
    markdown: page.source.markdown,
  };
}

/**
 * The single, shared presentation rule for what to show as a page's label
 * — the one owner every rendering surface (sidebar, page header, and
 * eventually search/backlinks/references/recent notes) calls instead of
 * reading page.name directly or re-deriving its own fallback logic.
 *
 * Priority, shared by Notes and Daily Notes rather than two separate
 * systems: explicit filename -> description -> primary body content ->
 * placeholder. The only type-aware step is what counts as "the filename
 * is meaningful": a Note's filename can be a deliberate user choice, so
 * it's checked against isAutoGeneratedName; a Daily Note's filename
 * is always a deterministic date, never chosen, so it never qualifies —
 * that's what keeps the date out of the label without a second chain.
 * An empty name (only reachable via an untitled EffectivePage draft —
 * no persisted Page's filename is ever empty) is excluded the same way,
 * so a fresh draft falls through to description/content/placeholder
 * instead of rendering a blank title.
 *
 * Presentation-only: never persisted, never touches Vault, and must never
 * be used for search matching, wiki-link resolution, or indexing, all of
 * which continue to resolve against the real page.name.
 */
export function getPageDisplayLabel(page: PageDisplayLabelInput): PageDisplayLabel {
  if (
    page.type !== 'daily-note' &&
    page.name.trim().length > 0 &&
    !isAutoGeneratedName(page.name)
  ) {
    return { text: page.name, source: 'title' };
  }

  const description = page.description?.trim();

  if (description) {
    return { text: description, source: 'description' };
  }

  const content = getPrimaryDisplayText(page.markdown);

  if (content) {
    return { text: content, source: 'content' };
  }

  return {
    text: getPageTitlePlaceholder(page.type),
    source: 'placeholder',
  };
}

/**
 * The single owner of "which title styling does a label get." Styling
 * tracks only whether real user content exists: 'title', 'description',
 * and 'content' are all things the user actually wrote, so they render
 * as 'default'. Only the literal placeholder fallback ("New Note" /
 * "Start typing...") — meaning nothing was available at all — renders
 * as 'placeholder'. This is the same rule for Notes and Daily Notes.
 *
 * Every rendering surface that shows a PageDisplayLabel calls this
 * instead of comparing label.source itself, so the distinction can't
 * drift between call sites.
 */
export function getPageDisplayLabelStyle(
  label: PageDisplayLabel
): 'default' | 'placeholder' {
  return label.source === 'placeholder' ? 'placeholder' : 'default';
}
