import type { Page } from '../vault/models/Page';
import { isAutoGeneratedNoteName } from '../shared/naming/AutoGeneratedPageName';
import { getPrimaryDisplayText } from './getPrimaryDisplayText';

export type PageDisplayLabelSource = 'title' | 'description' | 'content' | 'placeholder';

export interface PageDisplayLabel {
  readonly text: string;
  readonly source: PageDisplayLabelSource;
}

/**
 * The single, shared presentation rule for what to show as a page's label
 * — the one owner every rendering surface (sidebar, page header, and
 * eventually search/backlinks/references/recent notes) calls instead of
 * reading page.name directly or re-deriving its own fallback logic.
 *
 * Priority, shared by Notes and Daily Notes rather than two separate
 * systems: explicit filename -> description -> primary body content ->
 * placeholder. The only type-aware step is what counts as "the filename
 * is meaningful": a Note's filename can be a deliberate user choice, so
 * it's checked against isAutoGeneratedNoteName; a Daily Note's filename
 * is always a deterministic date, never chosen, so it never qualifies —
 * that's what keeps the date out of the label without a second chain.
 *
 * Presentation-only: never persisted, never touches Vault, and must never
 * be used for search matching, wiki-link resolution, or indexing, all of
 * which continue to resolve against the real page.name.
 */
export function getPageDisplayLabel(page: Page): PageDisplayLabel {
  if (page.type !== 'daily-note' && !isAutoGeneratedNoteName(page.name)) {
    return { text: page.name, source: 'title' };
  }

  const description = page.metadata.description?.trim();

  if (description) {
    return { text: description, source: 'description' };
  }

  const content = getPrimaryDisplayText(page.source.markdown);

  if (content) {
    return { text: content, source: 'content' };
  }

  return {
    text: page.type === 'daily-note' ? 'Daily Note' : 'New Note',
    source: 'placeholder',
  };
}

/**
 * The single owner of "which title styling does a label get." Semantic,
 * not literal: 'default' means "this is the page's explicit title,"
 * 'placeholder' means "Clutter inferred this to help identify the page" —
 * covering description and content-derived labels too, not only the
 * literal placeholder fallback. Every rendering surface that shows a
 * PageDisplayLabel calls this instead of comparing source === 'placeholder'
 * itself, so the distinction can't drift between call sites.
 */
export function getPageDisplayLabelStyle(
  label: PageDisplayLabel
): 'default' | 'placeholder' {
  return label.source === 'title' ? 'default' : 'placeholder';
}
