import type { Folder } from '../vault/models/Folder';
import { isAutoGeneratedName } from '../shared/naming/AutoGeneratedName';

/**
 * True only for a Folder whose name is still the collision-avoidance
 * default ("Untitled"/"Untitled 2"/...) — i.e. the user has never given it
 * a deliberate name, or cleared it back out during a rename (see
 * FolderPathResolver.resolveRenamePath). The folder-side counterpart to
 * isNoteUntitled — same predicate, same shared isAutoGeneratedName check,
 * no Folder-specific exception the way Daily Notes are for Notes.
 */
export function isFolderUntitled(folder: Folder): boolean {
  return isAutoGeneratedName(folder.name);
}
