import type { Page } from '../vault/models/Page';
import { isAutoGeneratedNoteName } from '../shared/naming/AutoGeneratedPageName';

/**
 * True only for a regular Note whose filename is still the
 * collision-avoidance default ("Untitled"/"Untitled 2"/...) — i.e. the
 * user has never given it a deliberate title. This is Category B's
 * predicate (editing/identity surfaces: page header, breadcrumb, future
 * rename flows) — it answers "does this page still need a title,"
 * not "what's interesting to show while browsing."
 *
 * Always false for Daily Notes, and deliberately not shared with
 * getPageDisplayLabel's internal check even though both look at the same
 * fact (a Daily Note's filename is a date). getPageDisplayLabel (Category
 * A, browse surfaces) suppresses the date because it's redundant next to
 * existing UI chrome — a day badge, month grouping. This predicate is
 * about identity, not what's redundant to preview: a Daily Note's
 * filename is its real, permanent, correct identity, never something left
 * "unset" the way an unnamed Note's is. The two rules are allowed to
 * disagree about the same underlying fact because they answer different
 * questions.
 */
export function isNoteUntitled(page: Page): boolean {
  return page.type === 'note' && isAutoGeneratedNoteName(page.name);
}
