import { Vault } from '../../vault/models/Vault';
import { resolveEntityName } from '../../shared/naming/AutoGeneratedName';
import { resolveCollisionFreeName } from '../../shared/naming/resolveCollisionFreeName';
import { resolveFolderPathOrRoot } from './resolveFolderPathOrRoot';
import { VaultPath } from '../ingest/VaultPath';

export interface ResolvedCreateFolderPath {
  readonly path: string;
  readonly parentId: string | null;
}

export interface ResolvedRenamePath {
  readonly path: string;
  readonly parentId: string | null;
}

/**
 * Computes a collision-free destination path for a newly created folder.
 *
 * Pure with respect to the filesystem — it only reads the Vault's current
 * folder state, never touches disk. Mirrors PagePathResolver exactly, one
 * aggregate over.
 */
export class FolderPathResolver {
  constructor(private readonly vault: Vault) {}

  createFolderPath(parentId: string | null, name: string): ResolvedCreateFolderPath {
    const parentPath = resolveFolderPathOrRoot(this.vault, parentId);

    const candidateName = resolveEntityName(
      name,
      (candidate) => this.vault.getFolderByPath(`${parentPath}/${candidate}`) !== undefined
    );

    return {
      path: `${parentPath}/${candidateName}`,
      parentId,
    };
  }

  /**
   * Computes a collision-free destination path for renaming an existing
   * folder in place (ADR-024's interim 'rename-folder' kind — same parent
   * only, never reparents). The folder's own current path is excluded from
   * the collision check, so renaming to the same name (a no-op) resolves
   * to the folder's existing path rather than appending " 2" against
   * itself.
   *
   * An empty/whitespace-only name resolves through resolveEntityName to a
   * fresh generated default ("Untitled"/"Untitled 2"/...), never back to
   * the folder's own current name — a folder whose name is cleared during
   * editing must immediately receive a real generated name internally, not
   * silently keep its old one.
   */
  resolveRenamePath(folderId: string, name: string): ResolvedRenamePath {
    const folder = this.vault.getFolder(folderId);

    if (!folder) {
      throw new Error(`Folder not found: ${folderId}`);
    }

    const parentPath = resolveFolderPathOrRoot(this.vault, folder.parentId);

    const candidateName = resolveEntityName(name, (candidate) => {
      const occupant = this.vault.getFolderByPath(`${parentPath}/${candidate}`);
      return occupant !== undefined && occupant.id !== folderId;
    });

    return {
      path: `${parentPath}/${candidateName}`,
      parentId: folder.parentId,
    };
  }

  /**
   * Computes a collision-free destination path for duplicating an existing
   * folder in place (same parent — FolderOperations.duplicate() is the
   * only intended caller). Unlike createFolderPath(), this never resolves
   * a parentId: Duplicate is a raw filesystem copy reconciled by
   * VaultSyncService, not a Gate `create-folder`, so the destination's
   * parentId is resolved there, not here (see ADR-028).
   */
  duplicateFolderPath(sourcePath: string): string {
    const parentPath = VaultPath.parentDirectory(sourcePath);
    const baseName = `${VaultPath.filename(sourcePath)} copy`;

    const candidateName = resolveCollisionFreeName(
      baseName,
      (candidate) => this.vault.getFolderByPath(`${parentPath}/${candidate}`) !== undefined
    );

    return `${parentPath}/${candidateName}`;
  }
}
