import { Vault } from '../../vault/models/Vault';
import { resolveEntityName } from '../../shared/naming/AutoGeneratedName';
import { resolveArchiveCollisionFreeName } from '../../shared/naming/archiveCollisionName';
import { resolveFolderPathOrRoot } from './resolveFolderPathOrRoot';
import { VaultPath } from '../ingest/VaultPath';

export interface ResolvedCreateFolderPath {
  readonly path: string;
  readonly parentId: string | null;
}

export interface ResolvedRenamePath {
  readonly path: string;
  readonly parentId: string | null;
}

/**
 * Computes a collision-free destination path for a newly created folder.
 *
 * Pure with respect to the filesystem — it only reads the Vault's current
 * folder state, never touches disk. Mirrors PagePathResolver exactly, one
 * aggregate over.
 *
 * Duplicate does not use this resolver (ADR-029): its destination name is
 * a provider decision (VaultFileSystem.duplicate()), never computed in
 * Application.
 */
export class FolderPathResolver {
  constructor(private readonly vault: Vault) {}

  createFolderPath(parentId: string | null, name: string): ResolvedCreateFolderPath {
    const parentPath = resolveFolderPathOrRoot(this.vault, parentId);

    const candidateName = resolveEntityName(
      name,
      (candidate) => this.vault.getFolderByPath(`${parentPath}/${candidate}`) !== undefined
    );

    return {
      path: `${parentPath}/${candidateName}`,
      parentId,
    };
  }

  /**
   * Computes a collision-free destination path for renaming an existing
   * folder in place (ADR-024's interim 'rename-folder' kind — same parent
   * only, never reparents). The folder's own current path is excluded from
   * the collision check, so renaming to the same name (a no-op) resolves
   * to the folder's existing path rather than appending " 2" against
   * itself.
   *
   * An empty/whitespace-only name resolves through resolveEntityName to a
   * fresh generated default ("Untitled"/"Untitled 2"/...), never back to
   * the folder's own current name — a folder whose name is cleared during
   * editing must immediately receive a real generated name internally, not
   * silently keep its old one.
   */
  /**
   * ADR-026 §3: the folder-scoped equivalent of
   * MoveService.resolveArchiveDestination — same reserved-folder lookup, no
   * hardcoded path literal, and (same follow-up as the page-side method)
   * the same shared resolveArchiveCollisionFreeName rule: two folders with
   * the same name at different locations (e.g. `Project/` and
   * `OldProject/Project/`) both flattening to `Archive/Project` on archive
   * is the folder-shaped instance of the exact collision
   * MoveService.resolveArchiveDestination's doc comment describes — same
   * fix, same helper, not a parallel folder-specific rule. Unlike a page's
   * archive (which flattens to `Archive/<filename>`), a folder can't
   * flatten (it's a container, not a leaf, ADR-026 §0) — the destination
   * keeps the folder's own basename (collision permitting), so
   * `Vault.moveFolder`'s cascade (invoked by archiveFolder()) relocates the
   * whole subtree under it with internal structure intact.
   */
  resolveArchiveDestination(folderId: string): { path: string; parentId: string } {
    const folder = this.vault.getFolder(folderId);

    if (!folder) {
      throw new Error(`Folder not found: ${folderId}`);
    }

    const archiveFolder = this.vault.getReservedFolder('archive');

    if (!archiveFolder) {
      throw new Error(`Archive folder not found: ${this.vault.root}/Archive`);
    }

    const candidateName = resolveArchiveCollisionFreeName(
      folder.name,
      (candidate) => {
        const occupant = this.vault.getFolderByPath(`${archiveFolder.path}/${candidate}`);
        return occupant !== undefined && occupant.id !== folderId;
      },
      new Date()
    );

    return {
      path: `${archiveFolder.path}/${candidateName}`,
      parentId: archiveFolder.id,
    };
  }

  /**
   * The folder-scoped equivalent of MoveService.resolveRestoreDestination —
   * same rule, exactly: `folder.metadata.originalPath` (stored verbatim at
   * archive time) is the sole source of truth, never `originalParentId`.
   * If that path's containing directory still exists, restore there; else
   * vault root. No Inbox fallback — exactly two outcomes, same as the page
   * contract this mirrors.
   */
  resolveRestoreDestination(folderId: string): { path: string; parentId: string | null } {
    const folder = this.vault.getFolder(folderId);

    if (!folder) {
      throw new Error(`Folder not found: ${folderId}`);
    }

    const originalPath = folder.metadata.originalPath;

    if (originalPath !== null) {
      const parentDirectory = VaultPath.parentDirectory(originalPath);

      if (parentDirectory === this.vault.root) {
        return { path: originalPath, parentId: null };
      }

      const originalFolder = this.vault.getFolderByPath(parentDirectory);

      if (originalFolder) {
        return { path: originalPath, parentId: originalFolder.id };
      }
    }

    return {
      path: `${this.vault.root}/${folder.name}`,
      parentId: null,
    };
  }

  resolveRenamePath(folderId: string, name: string): ResolvedRenamePath {
    const folder = this.vault.getFolder(folderId);

    if (!folder) {
      throw new Error(`Folder not found: ${folderId}`);
    }

    const parentPath = resolveFolderPathOrRoot(this.vault, folder.parentId);

    const candidateName = resolveEntityName(name, (candidate) => {
      const occupant = this.vault.getFolderByPath(`${parentPath}/${candidate}`);
      return occupant !== undefined && occupant.id !== folderId;
    });

    return {
      path: `${parentPath}/${candidateName}`,
      parentId: folder.parentId,
    };
  }
}
