import type { Page } from '../models/Page';
import { Vault } from '../models/Vault';
import type { VaultFileSystem } from '../providers/VaultFileSystem';
import { VaultPath } from '../ingest/VaultPath';
import { resolveEntityName } from '../../shared/naming/AutoGeneratedName';
import { resolveCollisionFreeName } from '../../shared/naming/resolveCollisionFreeName';
import { resolveArchiveCollisionFreeName } from '../../shared/naming/archiveCollisionName';
import { resolveFolderPathOrRoot } from './resolveFolderPathOrRoot';
import { isDailyNotesFolderOrDescendant } from '../initialize/ReservedResources';

export class MoveService {
  constructor(
    private readonly vault: Vault,
    private readonly fileSystem: VaultFileSystem
  ) {}

  /**
   * Computes where an archived copy of `current` should live, based on the
   * vault's reserved Archive folder. Path/parentId only — does not move
   * anything itself (see movePage).
   *
   * Flattening every archived page into one directory means two pages that
   * legitimately coexist today (same filename, different folders — e.g.
   * `Project/Test.md` and `OldProject/Test.md`) can collide once both are
   * archived. The common case (destination free) is untouched: same
   * filename, no rename. Only on an actual collision does
   * resolveArchiveCollisionFreeName fall back to a local-time timestamp
   * suffix — never an id, never a counter alone — so Restore (which reads
   * `originalPath`, never this filename) is completely unaffected.
   */
  resolveArchiveDestination(current: Page): {
    path: string;
    parentId: string;
  } {
    // ReservedResources.ts, via Vault.getReservedFolder(), is the one
    // place the Archive folder's identity/path is defined — no hardcoded
    // path literal here (ADR-023's audit found this file and
    // ArchiveMetadataReconciler.ts independently hardcoding the same
    // "${vault.root}/Archive" string).
    const archiveFolder = this.vault.getReservedFolder('archive');

    if (!archiveFolder) {
      throw new Error(`Archive folder not found: ${this.vault.root}/Archive`);
    }

    const baseName = VaultPath.pageName(current.path);

    const candidateName = resolveArchiveCollisionFreeName(
      baseName,
      (candidate) => {
        const occupant = this.vault.getPageByPathCaseInsensitive(
          `${archiveFolder.path}/${candidate}.md`
        );
        return occupant !== undefined && occupant.id !== current.id;
      },
      new Date()
    );

    return {
      path: `${archiveFolder.path}/${candidateName}.md`,
      parentId: archiveFolder.id,
    };
  }

  /**
   * Computes where an archived page should return to: its exact original
   * path if that path's containing folder still exists, else the vault
   * root. `metadata.originalPath` (stored verbatim at archive time) is the
   * sole source of truth — deliberately not `originalParentId`, so this
   * survives the original folder being deleted and a new one later
   * recreated at the same path (a new id, but the same path), and
   * deliberately does not survive the original folder merely being
   * renamed (its id unchanged, but nothing exists at the old path
   * anymore) — that trade-off is the approved contract, not an oversight.
   * No Inbox fallback: exactly two outcomes, original path or vault root.
   */
  resolveRestoreDestination(current: Page): {
    path: string;
    parentId: string | null;
  } {
    const originalPath = current.metadata.originalPath;

    if (originalPath !== null) {
      const parentDirectory = VaultPath.parentDirectory(originalPath);

      if (parentDirectory === this.vault.root) {
        return { path: originalPath, parentId: null };
      }

      const originalFolder = this.vault.getFolderByPath(parentDirectory);

      if (originalFolder) {
        return { path: originalPath, parentId: originalFolder.id };
      }
    }

    const filename = VaultPath.filename(current.path);

    return {
      path: `${this.vault.root}/${filename}`,
      parentId: null,
    };
  }

  /**
   * Computes where `current` should live if moved into an arbitrary
   * destination folder, preserving its filename. Path/parentId only —
   * does not move anything itself (see movePage).
   *
   * Daily Notes is opaque to Move (approved contract): a destination
   * inside — or equal to — the reserved Daily Notes folder is rejected
   * here, at the one place every Move destination for a page is resolved,
   * so no caller (UI or otherwise) can reach it even by bypassing the
   * Folder Picker's own exclusion of the same folder.
   *
   * `destinationFolderId: null` means the vault root — the same
   * root-as-null convention Folder.parentId and
   * FolderPathResolver.resolveMoveDestination's destinationFolderId
   * already use, extended here so a note (approved Move contract: "moves
   * between normal workspace folders and the vault root") isn't limited
   * to a real folder id the way this method originally shipped
   * (ADR-013's Move backend, built before the destination-picker UI, only
   * ever needed a real folder id — the root case has no UI caller until
   * now).
   */
  resolveMoveDestination(
    current: Page,
    destinationFolderId: string | null
  ): { path: string; parentId: string | null } {
    const destinationPath = resolveFolderPathOrRoot(this.vault, destinationFolderId);

    if (isDailyNotesFolderOrDescendant(this.vault.root, destinationPath)) {
      throw new Error(`Cannot move into Daily Notes: ${destinationPath}`);
    }

    const baseName = VaultPath.pageName(current.path);

    const candidateName = resolveCollisionFreeName(
      baseName,
      (candidate) => {
        const occupant = this.vault.getPageByPathCaseInsensitive(
          `${destinationPath}/${candidate}.md`
        );
        return occupant !== undefined && occupant.id !== current.id;
      },
      { firstSuffix: 1 }
    );

    return {
      path: `${destinationPath}/${candidateName}.md`,
      parentId: destinationFolderId,
    };
  }

  /**
   * Computes a collision-free destination path for renaming `current` in
   * place — same parent only, never reparents. The page-side counterpart
   * to FolderPathResolver.resolveMoveDestination's same-parent case, one
   * aggregate over; lives here (not PagePathResolver, application layer)
   * because the Persistence Gate is this method's only caller, and the
   * Gate must never depend upward on the application layer (rule 7) —
   * every other page-destination resolver the Gate already uses
   * (resolveArchiveDestination, resolveRestoreDestination,
   * resolveMoveDestination) lives in this same file for the same reason.
   *
   * `current`'s own path is excluded from the collision check, so renaming
   * to the same title (a no-op) resolves to its existing path rather than
   * appending " 2" against itself.
   *
   * An empty/whitespace-only title resolves through resolveEntityName to a
   * fresh generated default ("Untitled"/"Untitled 2"/...), never back to
   * the page's own current name — same reasoning, and same shared
   * implementation, as FolderPathResolver.resolveMoveDestination.
   */
  resolveRenameDestination(
    current: Page,
    title: string
  ): { path: string; parentId: string | null } {
    const folderPath = resolveFolderPathOrRoot(this.vault, current.parentId);

    const candidateName = resolveEntityName(title, (candidate) => {
      const occupant = this.vault.getPageByPathCaseInsensitive(`${folderPath}/${candidate}.md`);
      return occupant !== undefined && occupant.id !== current.id;
    });

    return {
      path: `${folderPath}/${candidateName}.md`,
      parentId: current.parentId,
    };
  }

  async movePage(current: Page, updated: Page): Promise<void> {
    const existing = this.vault.getPage(updated.id);

    if (!existing) {
      throw new Error(`Page not found: ${updated.id}`);
    }

    if (
      current.path === updated.path &&
      current.parentId === updated.parentId
    ) {
      return;
    }

    const occupant = this.vault.getPageByPathCaseInsensitive(updated.path);

    if (occupant && occupant.id !== updated.id) {
      throw new Error(`Path already in use by another page: ${updated.path}`);
    }

    if (current.path !== updated.path) {
      const destinationDirectory = VaultPath.parentDirectory(updated.path);

      if (
        destinationDirectory &&
        !(await this.fileSystem.exists(destinationDirectory))
      ) {
        await this.fileSystem.createDirectory(destinationDirectory);
      }

      await this.fileSystem.moveFile(current.path, updated.path);
    }

    this.vault.updatePagePath(updated.id, updated.path, updated.parentId);
  }
}
