import { describe, expect, it } from 'vitest';
import {
  AUTO_GENERATED_NAME_BASE,
  isAutoGeneratedName,
  resolveEntityName,
} from './AutoGeneratedName';

describe('isAutoGeneratedName', () => {
  it('is true for the bare base name', () => {
    expect(isAutoGeneratedName(AUTO_GENERATED_NAME_BASE)).toBe(true);
  });

  it('is true for numbered collision-avoidance variants', () => {
    expect(isAutoGeneratedName('Untitled 2')).toBe(true);
    expect(isAutoGeneratedName('Untitled 3')).toBe(true);
    expect(isAutoGeneratedName('Untitled 42')).toBe(true);
  });

  it('is false for a deliberately chosen name', () => {
    expect(isAutoGeneratedName('Meeting Notes')).toBe(false);
  });

  it('is false for a name that merely starts with the base name', () => {
    expect(isAutoGeneratedName('Untitled Project Plan')).toBe(false);
  });

  it('is false for malformed suffixes', () => {
    expect(isAutoGeneratedName('Untitled  2')).toBe(false); // double space
    expect(isAutoGeneratedName('Untitled2')).toBe(false); // no space
    expect(isAutoGeneratedName('Untitled a')).toBe(false); // non-numeric
  });

  it('is case-sensitive', () => {
    expect(isAutoGeneratedName('untitled')).toBe(false);
  });

  it('is true for Duplicate\'s "copy" suffix variants of the base name — still nothing the user actually named', () => {
    expect(isAutoGeneratedName('Untitled copy')).toBe(true);
    expect(isAutoGeneratedName('Untitled copy 2')).toBe(true);
    expect(isAutoGeneratedName('Untitled copy 10')).toBe(true);
  });

  it('is false for a deliberately named entity\'s own "copy" variants — that name is real, not generated', () => {
    expect(isAutoGeneratedName('Project')).toBe(false);
    expect(isAutoGeneratedName('Project 2')).toBe(false);
    expect(isAutoGeneratedName('Project copy')).toBe(false);
    expect(isAutoGeneratedName('Project copy 2')).toBe(false);
    expect(isAutoGeneratedName('Project copy 10')).toBe(false);
  });

  it('is false for malformed "copy" suffixes', () => {
    expect(isAutoGeneratedName('Untitled copycat')).toBe(false); // not a " copy" boundary
    expect(isAutoGeneratedName('Untitled copy a')).toBe(false); // non-numeric
    expect(isAutoGeneratedName('Untitled copy  2')).toBe(false); // double space
    expect(isAutoGeneratedName('Untitledcopy')).toBe(false); // no space
  });
});

describe('resolveEntityName', () => {
  it('returns the trimmed desired name when nothing is taken', () => {
    expect(resolveEntityName('Projects', () => false)).toBe('Projects');
  });

  it('trims surrounding whitespace off a deliberate name', () => {
    expect(resolveEntityName('  Projects  ', () => false)).toBe('Projects');
  });

  it('falls back to the generated base name when the desired name is empty', () => {
    expect(resolveEntityName('', () => false)).toBe('Untitled');
  });

  it('falls back to the generated base name when the desired name is whitespace-only', () => {
    expect(resolveEntityName('   ', () => false)).toBe('Untitled');
  });

  it('appends a numeric suffix when the generated base name is already taken', () => {
    const taken = new Set(['Untitled']);

    expect(resolveEntityName('', (name) => taken.has(name))).toBe('Untitled 2');
  });

  it('appends a numeric suffix when a deliberate name is already taken', () => {
    const taken = new Set(['Projects']);

    expect(resolveEntityName('Projects', (name) => taken.has(name))).toBe('Projects 2');
  });
});
