/**
 * The one place that knows what an auto-generated, collision-avoidance
 * note name looks like.
 *
 * Two independent concerns need this exact same definition and must never
 * drift apart: PagePathResolver (the generator, which mints these names to
 * resolve a collision-free path when a note is created without a
 * deliberate title) and getPageDisplayLabel (the presentation layer,
 * which decides whether a persisted filename represents real user intent
 * or should be treated as if the note were still unnamed).
 */
export const AUTO_GENERATED_NOTE_BASE_NAME = 'Untitled';

const AUTO_GENERATED_NOTE_NAME_PATTERN = new RegExp(
  `^${AUTO_GENERATED_NOTE_BASE_NAME}(?: \\d+)?$`
);

/**
 * True for "Untitled", "Untitled 2", "Untitled 3", ... — the exact shape
 * PagePathResolver.createNotePath produces when no deliberate title was
 * given. False for anything a user could plausibly have chosen on
 * purpose, including a name that merely starts with "Untitled".
 */
export function isAutoGeneratedNoteName(name: string): boolean {
  return AUTO_GENERATED_NOTE_NAME_PATTERN.test(name);
}
