import { resolveCollisionFreeName } from './resolveCollisionFreeName';

/**
 * The one place that knows what an auto-generated, collision-avoidance
 * default name looks like — shared by every named entity in the
 * application (Notes, Folders, and any future one), not just pages.
 *
 * Every concern that needs this exact same definition must never drift
 * apart: resolveEntityName below (the single owner of "empty name ->
 * generated default -> collision resolution," which every create/rename
 * path resolver calls to mint these names) and the presentation layer
 * (getPageDisplayLabel, getFolderDisplayLabel), which decides whether a
 * persisted name represents real user intent or should be treated as if
 * the entity were still unnamed.
 */
export const AUTO_GENERATED_NAME_BASE = 'Untitled';

const AUTO_GENERATED_NAME_PATTERN = new RegExp(`^${AUTO_GENERATED_NAME_BASE}(?: \\d+)?$`);

/**
 * True for "Untitled", "Untitled 2", "Untitled 3", ... — the exact shape
 * resolveEntityName produces when no deliberate name was given. False for
 * anything a user could plausibly have chosen on purpose, including a name
 * that merely starts with "Untitled".
 */
export function isAutoGeneratedName(name: string): boolean {
  return AUTO_GENERATED_NAME_PATTERN.test(name);
}

/**
 * The single canonical owner of "empty name -> generated default name ->
 * collision resolution." Every create/rename path resolver (PagePathResolver,
 * FolderPathResolver's create and rename, MoveService's page rename) calls
 * this instead of independently trimming and falling back to its own
 * default before calling resolveCollisionFreeName — that duplication is
 * exactly what previously let some of those call sites fall back to the
 * entity's *old* name (or a one-off literal) on an empty rename instead of
 * regenerating a proper default.
 *
 * `desiredName` is the raw, possibly-empty user input; `isTaken` is the
 * caller's own collision predicate (already scoped to the right sibling
 * set and, for a rename, already excluding the entity's own current name/
 * path from counting as taken).
 */
export function resolveEntityName(
  desiredName: string,
  isTaken: (candidateName: string) => boolean
): string {
  const baseName = desiredName.trim() || AUTO_GENERATED_NAME_BASE;

  return resolveCollisionFreeName(baseName, isTaken);
}
