import { describe, expect, it } from 'vitest';
import {
  AUTO_GENERATED_NOTE_BASE_NAME,
  isAutoGeneratedNoteName,
} from './AutoGeneratedPageName';

describe('isAutoGeneratedNoteName', () => {
  it('is true for the bare base name', () => {
    expect(isAutoGeneratedNoteName(AUTO_GENERATED_NOTE_BASE_NAME)).toBe(true);
  });

  it('is true for numbered collision-avoidance variants', () => {
    expect(isAutoGeneratedNoteName('Untitled 2')).toBe(true);
    expect(isAutoGeneratedNoteName('Untitled 3')).toBe(true);
    expect(isAutoGeneratedNoteName('Untitled 42')).toBe(true);
  });

  it('is false for a deliberately chosen title', () => {
    expect(isAutoGeneratedNoteName('Meeting Notes')).toBe(false);
  });

  it('is false for a name that merely starts with the base name', () => {
    expect(isAutoGeneratedNoteName('Untitled Project Plan')).toBe(false);
  });

  it('is false for malformed suffixes', () => {
    expect(isAutoGeneratedNoteName('Untitled  2')).toBe(false); // double space
    expect(isAutoGeneratedNoteName('Untitled2')).toBe(false); // no space
    expect(isAutoGeneratedNoteName('Untitled a')).toBe(false); // non-numeric
  });

  it('is case-sensitive', () => {
    expect(isAutoGeneratedNoteName('untitled')).toBe(false);
  });
});
