import type { ReactNode, RefObject } from 'react';
import './Page.css';
import { PageCover } from './cover/Page.Cover';
import { PageTopBar } from './topbar/Page.TopBar';
import { PageTitleSection } from './header/Page.TitleSection';
import { PageTitle } from './header/Page.Title';
import { PageDescription } from './header/Page.Description';

type PageProps = {
  /**
   * Omitted entirely (not empty-string) renders no title section at all —
   * for a resource viewer page (e.g. Image Resource Page), which has no
   * document identity to name/edit. An empty string still renders the
   * title field with its placeholder, unchanged from today's behavior.
   */
  title?: string;
  description?: string;
  titleEditable?: boolean;
  titlePlaceholder?: string;
  breadcrumbs?: ReactNode;
  menu?: ReactNode;
  actions?: ReactNode;
  body?: ReactNode;
  coverImage?: string;
  /**
   * A handle onto whatever's rendered in `body`, so title's Enter can
   * advance focus into it — Page doesn't need to know what body actually
   * is (MarkdownEditor today, a future page type's own editing surface
   * later), only that it can be focused.
   */
  bodyFocusRef?: RefObject<{ focus(): void } | null>;
  /**
   * Fired when a changed title commits (see PageTitle.onCommit). Supplied
   * by the draft branch and the folder branch (FolderOperations.rename(),
   * ADR-024) — both discrete-commit consumers. A persisted Note supplies
   * onTitleEdit/onTitleFlush instead (below), not this.
   */
  onTitleCommit?(title: string): void;
  /** See PageTitle.onEdit — the continuous-commit entry point for a channel-backed title (persisted Note, folder). */
  onTitleEdit?(title: string): void;
  /** See PageTitle.onFlush — the non-escaped-blur-flush entry point for a channel-backed title. */
  onTitleFlush?(): void;
  /** See PageTitle.onCancel — the Escape entry point for a channel-backed title, reverting its pending value. */
  onTitleCancel?(): void;
  /** Forwarded to PageTopBar's sidebar-toggle button — see PageTopBarProps. */
  isSidebarVisible?: boolean;
  onToggleSidebarVisible?(): void;
  /**
   * Forwarded to PageTopBar's history buttons — the Workspace-owned
   * navigation-history state and NavigationRouter.back()/forward() handlers
   * of ADR-027, which PageHost resolves and passes down. Optional for the
   * same reason the sidebar-toggle pair above is: Page's own tests and any
   * caller that doesn't care about history state shouldn't be forced to
   * supply them.
   */
  canNavigateBack?: boolean;
  canNavigateForward?: boolean;
  onNavigateBack?(): void;
  onNavigateForward?(): void;
  /**
   * React key for the title's EditableText, not for Page itself — PageHost
   * used to key the whole <Page> by activePageId so a fresh PageTitle
   * remounts per page (EditableText's autoFocus is deliberately mount-once,
   * per the commit that introduced this: "without it, navigating between
   * two persisted pages ... would silently stop the autofocus-on-missing-
   * title behavior from re-firing"). Scoping the key to just PageTitle
   * keeps that autofocus behavior without remounting the rest of Page on
   * every navigation.
   */
  titleKey?: string;
};

export function Page({
  title,
  description,
  titleEditable,
  titlePlaceholder,
  breadcrumbs,
  menu,
  actions,
  body,
  coverImage,
  bodyFocusRef,
  onTitleCommit,
  onTitleEdit,
  onTitleFlush,
  onTitleCancel,
  isSidebarVisible,
  onToggleSidebarVisible,
  // PageTopBar requires these four, so the defaults stand in for a caller
  // that omitted them: "no history in either direction," which renders both
  // buttons disabled and therefore makes the no-op handlers unreachable.
  canNavigateBack = false,
  canNavigateForward = false,
  onNavigateBack = () => {},
  onNavigateForward = () => {},
  titleKey,
}: PageProps) {
  // The one place "is this entity missing its title" is decided for the
  // editing/identity surface — driven entirely by the title string the
  // caller already resolved (empty means missing, per the same
  // isAutoGeneratedName-based convention toResourcePageModel/
  // getPageDisplayLabel/getFolderDisplayLabel each apply), not by any
  // page-type knowledge Page itself would otherwise need.
  const shouldAutoFocusTitle = Boolean(titleEditable) && title === '';
  const hasTitle = title !== undefined;

  return (
    <div className="page">
      <div className="page__document">
        <PageTopBar
          breadcrumbs={breadcrumbs}
          menu={menu}
          actions={actions}
          isSidebarVisible={isSidebarVisible}
          onToggleSidebarVisible={onToggleSidebarVisible}
          canNavigateBack={canNavigateBack}
          canNavigateForward={canNavigateForward}
          onNavigateBack={onNavigateBack}
          onNavigateForward={onNavigateForward}
        />
        <div className="page__content">
          {hasTitle && (
            <header className="page__header">
              <PageTitleSection>
                <PageTitle
                  key={titleKey}
                  editable={titleEditable}
                  placeholder={titlePlaceholder}
                  autoFocus={shouldAutoFocusTitle}
                  onSubmit={() => bodyFocusRef?.current?.focus()}
                  onCommit={onTitleCommit}
                  onEdit={onTitleEdit}
                  onFlush={onTitleFlush}
                  onCancel={onTitleCancel}
                >
                  {title}
                </PageTitle>
                {description && <PageDescription>{description}</PageDescription>}
              </PageTitleSection>
            </header>
          )}
          <main className="page__body">{body}</main>
        </div>
      </div>
      {coverImage && <PageCover src={coverImage} />}
    </div>
  );
}
