import type { FolderOperations } from '@core/application/folder/FolderOperations';
import type { EffectivePage, EffectivePageState } from '@core/application/page/EffectivePageState';
import type { PageOperations } from '@core/application/page/PageOperations';
import { isAutoGeneratedName } from '@core/shared/naming/AutoGeneratedName';
import { isValidCalendarDate } from '@shared/helpers/time/helpers/isValidCalendarDate';
import type { NewFolderContentLabels } from '../shortcuts/NewFolderContent';

/** What a Daily Note's template is called when its own title is just its date. */
export const DAILY_NOTE_TEMPLATE_NAME = 'Daily Note Template';

/** The "Create template" dialog's wording — the New folder dialog, reworded. */
export const CREATE_TEMPLATE_LABELS: NewFolderContentLabels = {
  title: 'Create template',
  nameLabel: 'Template name',
  namePlaceholder: 'Untitled',
  duplicateMessage: (name) => `A template named “${name}” already exists.`,
  submitLabel: 'Create template',
  failureMessage: 'Failed to create template.',
};

/**
 * What the dialog is prefilled with (the user edits both before saving): the source's own name and
 * description. A Daily Note's title is its date — a template named "2026-10-07" would be nonsense —
 * so it gets a generic name instead; an auto-generated "Untitled" name is left blank for the user.
 */
export function getCreateTemplateDefaults(
  source: Pick<EffectivePage, 'type' | 'name' | 'description'>
): { name: string; description: string } {
  const description = source.description ?? '';

  if (source.type === 'daily-note' && isValidCalendarDate(source.name)) {
    return { name: DAILY_NOTE_TEMPLATE_NAME, description };
  }

  return { name: isAutoGeneratedName(source.name) ? '' : source.name, description };
}

export interface CreateTemplateFromPageDeps {
  readonly pageOperations: Pick<PageOperations, 'create'>;
  readonly folderOperations: Pick<FolderOperations, 'ensureReservedFolder'>;
  readonly effectivePageState: Pick<EffectivePageState, 'getPage'>;
}

/**
 * "Create template": a NEW, independent Template made from a copy of the source's content. The
 * source is only read — never moved, converted or edited — and nothing is opened or navigated to.
 * Everything else is existing machinery: the Templates folder is ensured as every template entry
 * point does (ADR-030), and `PageOperations.create` writes the page (fresh identity, no source
 * metadata) with the body and description in the same create; being created inside Templates is
 * what makes it a Template (ADR-041). The body is the source's current Markdown, unsaved edits
 * included (EffectivePageState).
 */
export async function createTemplateFromPage(
  deps: CreateTemplateFromPageDeps,
  sourcePageId: string,
  input: { readonly name: string; readonly description?: string }
): Promise<string> {
  const source = deps.effectivePageState.getPage(sourcePageId);

  if (!source) {
    throw new Error(`Page not found: ${sourcePageId}`);
  }

  const templates = await deps.folderOperations.ensureReservedFolder('templates');

  return deps.pageOperations.create({
    folderId: templates.id,
    title: input.name,
    body: source.markdown,
    description: input.description,
    activate: false,
  });
}
