import type { FavoriteItem } from '../models/FavoriteItem';
import { Folder as FolderEntry } from './Folder';
import { Note as NoteEntry } from './Note';
import { buildResourceActionMenu } from '@core/presentation/resourceActions/buildResourceActionMenu';
import { buildPageMenuHandlers } from '../helpers/buildPageMenuHandlers';
import { applyFolderSortSelection, buildFolderMenuHandlers } from '../helpers/buildFolderMenuHandlers';
import { DEFAULT_SIDEBAR_SORT, type SidebarSort } from '@core/properties/sidebarSort';
import { isAutoGeneratedName } from '@core/shared/naming/AutoGeneratedName';
import {
  getFolderTitlePlaceholder,
  getPageTitlePlaceholder,
} from '@core/presentation/PageDisplayPlaceholders';
import type { SidebarRowActions } from './FolderTree';
import type { Workspace } from '@core/workspace/Workspace';
import type { ResolveTag, ResolveWikiLink } from '@features/markdown/editor/MarkdownEditor';
import type { ResolvePageEmbed } from '@features/markdown/render/blocks/pageEmbedResolution';

interface FavoriteListProps {
  items: FavoriteItem[];
  workspace: Workspace;
  onOpenPage(id: string): void;
  onOpenFolder(id: string): void;
  /**
   * Same shared object Sidebar.Notes.tsx builds for FolderTree — reused
   * here so a favorited row's overflow menu (archive/delete/duplicate/
   * move/toggle-favorite) dispatches through the exact same
   * PageOperations/FolderOperations calls, and so opening this row's menu
   * closes any other row's menu open elsewhere in the sidebar (shared
   * openMenuId). Optional so existing callers/tests that don't wire row
   * actions keep rendering the plain, unwired overflow button Note/Folder
   * already fall back to.
   */
  rowActions?: SidebarRowActions;
  /**
   * Same injected resolution boundary the page editor uses — see Note's
   * own prop doc comment. A favorited note's title is markdown-bearing
   * (getPageDisplayLabel's description/content fallbacks) the same way
   * FolderTree's rows are; a favorited folder's title is a plain name
   * (getFolderDisplayLabel), so only the note branch below uses these.
   */
  resolveWikiLink?: ResolveWikiLink;
  resolveTag?: ResolveTag;
  resolveEmbed?: ResolvePageEmbed;
  /**
   * The Notes tree's per-folder sort — the same state, so a favorited folder's Sort by is the
   * folder's own (a Favorites row lists no children, but the folder's tree row does).
   */
  getFolderSort?(folderId: string): SidebarSort | undefined;
  onFolderSortChange?(folderId: string, sort: SidebarSort): void;
}

/**
 * Favorites shows the SAME resource-action menu as the resource anywhere else (ADR-048): the
 * canonical builder on the same surface profile as the sidebar, the same id → operation handler
 * maps, the same inline rename channel. Nothing here is a Favorites-specific action or a
 * hand-picked list; a row differs only in being listed here — and in owning its own open-menu and
 * rename state (the favorite and tree rows for one id are two rows), supplied by the caller's
 * `rowActions` override.
 */

export function FavoriteList({
  items,
  workspace,
  onOpenPage,
  onOpenFolder,
  rowActions,
  resolveWikiLink,
  resolveTag,
  resolveEmbed,
  getFolderSort,
  onFolderSortChange,
}: FavoriteListProps) {
  return items.map((item) => {
    const isEditing = rowActions?.editingId === item.id;
    // The raw name is what is edited — never the display label (a note's label may come from its
    // description or content). An auto-generated name edits as empty, with the placeholder.
    const rawName = item.name ?? item.title;
    const hasGeneratedName = isAutoGeneratedName(rawName);

    if (item.type === 'note') {
      // Every item here is already a favorite (isFavorite hardcoded true) and always durable
      // (isDraft hardcoded false — a draft can never be favorited, see getFavoriteItems.ts). A
      // Template (a note in Templates) loses Move and Create template through the actions' own
      // availability, exactly as it does everywhere else.
      const menuItems = rowActions
        ? buildResourceActionMenu(
            'note',
            { isFavorite: true, isTemplate: item.isTemplate, status: 'active' },
            'favorites'
          )
        : undefined;

      return (
        <NoteEntry
          key={item.id}
          title={isEditing ? (hasGeneratedName ? '' : rawName) : item.title}
          titlePlaceholder={isEditing && hasGeneratedName ? getPageTitlePlaceholder('note') : undefined}
          titleStyle={item.titleStyle}
          emoji={item.emoji}
          resolveWikiLink={resolveWikiLink}
          resolveTag={resolveTag}
          resolveEmbed={resolveEmbed}
          selected={workspace.activePageId === item.id}
          // A row mid-rename must not also navigate on click.
          onClick={isEditing ? undefined : () => onOpenPage(item.id)}
          isEditing={isEditing}
          onTitleEdit={rowActions ? (value) => rowActions.onNoteTitleEdit(item.id, value) : undefined}
          onTitleFlush={rowActions ? () => rowActions.onNoteTitleFlush(item.id) : undefined}
          onTitleCancel={rowActions ? () => rowActions.onNoteTitleCancel(item.id) : undefined}
          onTitleCommit={rowActions ? (value) => rowActions.onNoteTitleCommit(item.id, value) : undefined}
          onTitleEditingEnd={rowActions ? () => rowActions.onRenameEnd() : undefined}
          menuItems={menuItems}
          menuOpen={rowActions?.openMenuId === item.id}
          onMenuOpenChange={
            rowActions
              ? (open) => (open ? rowActions.onOpenMenu(item.id) : rowActions.onCloseMenu())
              : undefined
          }
          onMenuSelect={
            rowActions
              ? (id) => buildPageMenuHandlers(rowActions, item.id, true)[id]?.()
              : undefined
          }
          moveDestinations={rowActions ? rowActions.noteMoveDestinations : undefined}
          onMove={
            rowActions
              ? (destinationFolderId) => rowActions.onMoveNote(item.id, destinationFolderId)
              : undefined
          }
          onCreateFolder={rowActions ? rowActions.onCreateFolder : undefined}
          onChangeIcon={
            rowActions
              ? (emoji) => rowActions.onChangeNoteIcon(item.id, emoji)
              : undefined
          }
        />
      );
    }

    const menuItems = rowActions
      ? buildResourceActionMenu(
          'folder',
          {
            status: item.status ?? 'active',
            isFavorite: true,
            moveZone: item.moveZone,
            // The folder's own Sort by, as on its tree row.
            sort: onFolderSortChange ? (getFolderSort?.(item.id) ?? DEFAULT_SIDEBAR_SORT) : undefined,
          },
          'favorites'
        )
      : undefined;

    return (
      <FolderEntry
        key={item.id}
        title={isEditing ? (hasGeneratedName ? '' : rawName) : item.title}
        titlePlaceholder={isEditing && hasGeneratedName ? getFolderTitlePlaceholder() : undefined}
        emoji={item.emoji}
        hasCaret={false}
        selected={workspace.activeFolderId === item.id}
        onClick={isEditing ? undefined : () => onOpenFolder(item.id)}
        isEditing={isEditing}
        onTitleEdit={rowActions ? (value) => rowActions.onFolderTitleEdit(item.id, value) : undefined}
        onTitleFlush={rowActions ? () => rowActions.onFolderTitleFlush(item.id) : undefined}
        onTitleCancel={rowActions ? () => rowActions.onFolderTitleCancel(item.id) : undefined}
        onTitleCommit={rowActions ? (value) => rowActions.onFolderTitleCommit(item.id, value) : undefined}
        onTitleEditingEnd={rowActions ? () => rowActions.onRenameEnd() : undefined}
        menuItems={menuItems}
        menuOpen={rowActions?.openMenuId === item.id}
        onMenuOpenChange={
          rowActions
            ? (open) => (open ? rowActions.onOpenMenu(item.id) : rowActions.onCloseMenu())
            : undefined
        }
        onMenuSelect={
          rowActions
            ? (id) => {
                if (
                  applyFolderSortSelection(id, item.id, getFolderSort?.(item.id), onFolderSortChange)
                ) {
                  return;
                }

                buildFolderMenuHandlers(rowActions, item.id, true)[id]?.();
              }
            : undefined
        }
        moveDestinations={
          rowActions ? rowActions.getFolderMoveDestinations(item.id) : undefined
        }
        onMove={
          rowActions
            ? (destinationFolderId) => rowActions.onMoveFolder(item.id, destinationFolderId)
            : undefined
        }
        onCreateFolder={
          rowActions ? rowActions.createFolderInZone(item.moveZone ?? 'workspace') : undefined
        }
        onChangeIcon={
          rowActions
            ? (emoji) => rowActions.onChangeFolderIcon(item.id, emoji)
            : undefined
        }
      />
    );
  });
}
