// React
import { Fragment } from 'react/jsx-runtime';
// Components
import { Folder as FolderEntry } from './Folder';
import { Note as NoteEntry } from './Note';
import { Resource as ResourceEntry } from './Resource';
import { NewFolderRow } from './NewFolderRow';
import { buildNoteSidebarMenu } from './noteSidebarMenu.config';
import { buildFolderSidebarMenu } from './folderSidebarMenu.config';
import { buildResourceSidebarMenu } from './resourceSidebarMenu.config';
import { testIds } from '@shared/testing/selectors';
// Models
import type { Folder } from '@core/vault/models';
import type { VaultResource } from '@core/vault/models/VaultResource';
// Presentation
import {
  getPageDisplayLabel,
  getPageDisplayLabelStyle,
} from '@core/presentation/getPageDisplayLabel';
import { getFolderDisplayLabel } from '@core/presentation/getFolderDisplayLabel';
import {
  getFolderTitlePlaceholder,
  getPageTitlePlaceholder,
} from '@core/presentation/PageDisplayPlaceholders';
import { isAutoGeneratedName } from '@core/shared/naming/AutoGeneratedName';
import type { FolderPickerItem } from '@components/folder-picker/FolderPicker.types';
// Queries
import type { VaultQuery } from '@core/vault/queries/VaultQuery';
import type { Workspace } from '@core/workspace/Workspace';
import type { EffectivePage } from '@core/application/page/EffectivePageState';
import type { MembershipSelector } from '@core/application/membership/MembershipSelector';
import type { ResolveTag, ResolveWikiLink } from '@features/markdown/editor/MarkdownEditor';

export interface PendingNewFolder {
  // The parent under which a not-yet-persisted folder is being named.
  // null means the vault root.
  readonly parentId: string | null;
}

/**
 * Single owner of "which row's overflow menu/rename session is active,"
 * supplied by the caller (Sidebar.Notes.tsx) so it's shared across every
 * row FolderTree recurses through — the mechanism that guarantees only
 * one menu is ever open at a time, and threads every menu action back to
 * PageOperations/FolderOperations, the facades that already own rename/
 * archive/delete (no new write path is introduced by any handler here).
 * Optional so every existing FolderTree caller/test that doesn't wire row
 * actions keeps rendering the plain, unwired overflow button it always
 * has.
 */
export interface SidebarRowActions {
  openMenuId: string | null;
  onOpenMenu(id: string): void;
  onCloseMenu(): void;

  editingId: string | null;
  onStartRename(id: string): void;
  onRenameEnd(): void;

  /** Continuous-commit channel (PageOperations.commitTitle), persisted notes only. */
  onNoteTitleEdit(pageId: string, value: string): void;
  onNoteTitleFlush(pageId: string): void;
  onNoteTitleCancel(pageId: string): void;
  /**
   * Discrete Enter/blur-changed commit for a persisted note — a
   * synchronous canRename() pre-check only (PageOperations.canRename()),
   * returning false to reject a colliding title. Unlike a draft's commit,
   * this never itself persists: the continuous channel above already does
   * that, and PageOperations.rename() (which the continuous channel calls)
   * re-validates the same collision internally, so a duplicate can never
   * actually be written even if this pre-check and the continuous save
   * race each other.
   */
  onNoteTitleCommit(pageId: string, value: string): void | boolean;
  /** Discrete commit (PageOperations.updateDraftTitle), draft notes only. */
  onDraftTitleCommit(pageId: string, value: string): void | boolean;
  /**
   * No onDeleteNote/onDeleteFolder here — the sidebar menu configs
   * (noteSidebarMenu.config.ts/folderSidebarMenu.config.ts) never include a
   * 'delete' item (deletion-UX product decision: permanent Delete is
   * withdrawn from every ordinary workspace resource, and this row never
   * renders an archived one), so there is no dispatch target for it.
   */
  onArchiveNote(pageId: string): void;
  /** ADR-028 — a raw filesystem copy, see PageOperations.duplicate(). */
  onDuplicateNote(pageId: string): void;
  /**
   * Same PageOperations.updateMetadata({ favorite }) call the topbar's
   * favorite control and the Daily Notes sidebar's onToggleFavoriteNote
   * both dispatch to — one operation, shared across every entry point.
   * Takes the row's current favorite state (from its EffectivePage entry)
   * rather than looking it up separately.
   */
  onToggleFavoriteNote(pageId: string, isFavorite: boolean): void;
  /** PageOperations.updateMetadata({ icon }) — sidebar Change icon action. */
  onChangeNoteIcon(pageId: string, emoji: string | null): void;
  /**
   * Same Move flow as ResourceTopBarActions' (buildMoveDestinationItems.ts
   * + PageOperations.move) — a single destination list, since which
   * folders a note may move into doesn't depend on the note itself,
   * unlike a folder's own list (getFolderMoveDestinations below).
   */
  noteMoveDestinations: FolderPickerItem[];
  onMoveNote(pageId: string, destinationFolderId: string | null): void;
  /**
   * Shared by every Move entry point in the sidebar (note and folder
   * rows alike) — the same FolderOperations.create() the "+" button
   * already uses, just invoked from the Move picker's own "Create ..."
   * row instead. See MoveDestinationPicker's own doc comment for the
   * full create-then-select-then-close flow.
   */
  onCreateFolder(name: string): Promise<string>;

  /**
   * Discrete Enter/blur-changed commit for a folder — a synchronous
   * canRename() pre-check only (FolderOperations.canRename()), same shape
   * and reasoning as onNoteTitleCommit above: the continuous channel below
   * still does the actual persisting.
   */
  onFolderTitleCommit(folderId: string, value: string): void | boolean;
  /** Continuous-commit channel (FolderOperations.commitName), same shape as a persisted note's title. */
  onFolderTitleEdit(folderId: string, value: string): void;
  onFolderTitleFlush(folderId: string): void;
  onFolderTitleCancel(folderId: string): void;
  onArchiveFolder(folderId: string): void;
  /**
   * FolderOperations.updateMetadata({ favorite }) — the folder-scoped
   * counterpart to onToggleFavoriteNote above, same shared-call shape.
   * Takes the row's current favorite state (from `folder.metadata.favorite`)
   * rather than looking it up separately.
   */
  onToggleFavoriteFolder(folderId: string, isFavorite: boolean): void;
  /** FolderOperations.updateMetadata({ icon }) — sidebar Change icon action. */
  onChangeFolderIcon(folderId: string, emoji: string | null): void;
  /**
   * Per-folder — excludes that folder (and its own descendants) from its
   * own destination list, same as buildMoveDestinationItems.ts's
   * excludeFolderId does for the topbar's folder Move.
   */
  getFolderMoveDestinations(folderId: string): FolderPickerItem[];
  onMoveFolder(folderId: string, destinationFolderId: string | null): void;

  /**
   * Discrete-commit-only, mirroring a draft Note's onDraftTitleCommit shape
   * (no continuous channel — ResourceOperations.renameResource() is a
   * single one-shot Gate call, not a debounced autosave). Never returns
   * `false`: unlike onNoteTitleCommit/onFolderTitleCommit, a resource
   * rename never synchronously rejects a collision — it always dispatches,
   * relying entirely on MoveService.resolveResourceRenameDestination's
   * existing auto-suffix behavior, per the approved Resource mutation
   * design (no reject-on-collision rule for resources).
   */
  onResourceTitleCommit(resourceId: string, value: string): void;
  /**
   * ResourceOperations.archiveResource() — no confirmation dialog, same
   * shape as onArchiveNote (a resource, like a page, is always a single
   * leaf with no descendants, so it never needs the non-empty-folder
   * confirmation onArchiveFolder gates behind).
   */
  onArchiveResource(resourceId: string): void;
  /**
   * Same Move flow as noteMoveDestinations above — one shared destination
   * list, since which folders a resource may move into doesn't depend on
   * the resource itself, same reasoning noteMoveDestinations already
   * applies. Unlike noteMoveDestinations, this list also surfaces the
   * managed Assets/ folder as a selectable destination (normally hidden
   * from Note/Folder's own picker via MembershipSelector.
   * isAssetsStorageFolder) — moving a resource *into* Assets/ is one of
   * the required Resource Move destinations, per the approved design.
   */
  resourceMoveDestinations: FolderPickerItem[];
  onMoveResource(resourceId: string, destinationFolderId: string | null): void;
}

interface FolderTreeProps {
  // Folders only — folders have no draft concept (ADR-017 is scoped to
  // pages). Still threaded through (not read directly by this component
  // beyond passing it to the recursive call below) because the recursive
  // <FolderTree> instance needs it.
  query: VaultQuery;
  // ADR-023: the single owner of "is this folder part of Workspace" — used
  // for the true root's folder list (getWorkspaceFolders()) and, one layer
  // down, for dot-prefixed-name hiding via getVisibleChildFolders() — a
  // folder already inside a non-reserved folder is never itself a
  // reserved folder (nothing to classify one layer down for *that*
  // question), but a dot-prefixed name still needs hiding at every depth.
  membershipSelector: MembershipSelector;
  workspace: Workspace;
  // The folder whose children we're currently rendering.
  // null means "start from the root".
  parentId: string | null;
  // Used to indent nested folders.
  level: number;
  /**
   * Invoked when a durable page entry is selected.
   */
  onPageClick(pageId: string): void;
  /**
   * Invoked when a draft-only page entry is selected — distinct from
   * onPageClick because reopening a draft is a re-select
   * (Workspace.openPage), not PageOperations.open() (which requires a
   * Vault entry and would throw for a draft).
   */
  onDraftPageClick(pageId: string): void;
  /**
   * Invoked when a folder entry is selected.
   */
  onFolderClick(folder: Folder): void;
  /**
   * Invoked when a resource entry is clicked. Resource itself only ever
   * calls this for an image (a pdf row renders non-interactive) — see
   * Resource.tsx's own doc comment for why the click gating lives there,
   * not here.
   */
  onResourceClick?(resource: VaultResource): void;
  /**
   * Invoked when a folder row's "+" action is clicked — opens a new draft
   * note scoped to that folder (PageOperations.openDraft({ folderId })).
   */
  onCreateNote(folderId: string): void;
  /**
   * At most one folder-creation row is active anywhere in the tree at a
   * time. Every recursive level checks whether it owns this pending
   * folder's parentId, so root-level and nested creation share the exact
   * same mechanism rather than the root being special-cased.
   */
  pendingNewFolder: PendingNewFolder | null;
  onCommitNewFolder(name: string, parentId: string | null): void | boolean;
  onCancelNewFolder(): void;
  /** Overflow-menu/rename wiring — see SidebarRowActions. */
  rowActions?: SidebarRowActions;
  /** Same injected resolution boundary the page editor uses — see Note's own prop doc comment. */
  resolveWikiLink?: ResolveWikiLink;
  resolveTag?: ResolveTag;
}

function PageEntry({
  entry,
  level,
  workspace,
  onPageClick,
  onDraftPageClick,
  rowActions,
  resolveWikiLink,
  resolveTag,
}: {
  entry: EffectivePage;
  level: number;
  workspace: Workspace;
  onPageClick(pageId: string): void;
  onDraftPageClick(pageId: string): void;
  rowActions?: SidebarRowActions;
  resolveWikiLink?: ResolveWikiLink;
  resolveTag?: ResolveTag;
}) {
  const label = getPageDisplayLabel(entry);
  const isEditing = rowActions?.editingId === entry.id;
  const hasGeneratedName = isAutoGeneratedName(entry.name);
  const noteEditingValue = hasGeneratedName ? '' : entry.name;

  return (
    <NoteEntry
      data-testid={testIds.sidebar.noteItem(entry.id)}
      title={isEditing ? noteEditingValue : label.text}
      titlePlaceholder={
        isEditing && hasGeneratedName ? getPageTitlePlaceholder(entry.type) : undefined
      }
      titleStyle={getPageDisplayLabelStyle(label)}
      emoji={entry.icon}
      resolveWikiLink={resolveWikiLink}
      resolveTag={resolveTag}
      level={level}
      selected={workspace.activePageId === entry.id}
      // A row mid-rename must not also navigate on click — EditableText's
      // contenteditable surface isn't one of Entry's recognized
      // interactive-descendant tags, so leaving onClick wired here would
      // fire row selection on every click into the field.
      onClick={
        isEditing
          ? undefined
          : () => (entry.isDraft ? onDraftPageClick(entry.id) : onPageClick(entry.id))
      }
      isEditing={isEditing}
      onTitleEdit={
        !entry.isDraft && rowActions
          ? (value) => rowActions.onNoteTitleEdit(entry.id, value)
          : undefined
      }
      onTitleFlush={
        !entry.isDraft && rowActions ? () => rowActions.onNoteTitleFlush(entry.id) : undefined
      }
      onTitleCancel={
        !entry.isDraft && rowActions ? () => rowActions.onNoteTitleCancel(entry.id) : undefined
      }
      onTitleCommit={
        rowActions
          ? (value) =>
              entry.isDraft
                ? rowActions.onDraftTitleCommit(entry.id, value)
                : rowActions.onNoteTitleCommit(entry.id, value)
          : undefined
      }
      onTitleEditingEnd={rowActions ? () => rowActions.onRenameEnd() : undefined}
      menuItems={
        rowActions ? buildNoteSidebarMenu(entry.isDraft, entry.favorite) : undefined
      }
      menuOpen={rowActions?.openMenuId === entry.id}
      onMenuOpenChange={
        rowActions
          ? (open) => (open ? rowActions.onOpenMenu(entry.id) : rowActions.onCloseMenu())
          : undefined
      }
      onMenuSelect={
        rowActions
          ? (id) => {
              if (id === 'rename') {
                rowActions.onStartRename(entry.id);
              } else if (id === 'duplicate') {
                rowActions.onDuplicateNote(entry.id);
              } else if (id === 'toggle-favorite') {
                rowActions.onToggleFavoriteNote(entry.id, entry.favorite);
              } else if (id === 'archive') {
                rowActions.onArchiveNote(entry.id);
              }
            }
          : undefined
      }
      moveDestinations={
        rowActions && !entry.isDraft ? rowActions.noteMoveDestinations : undefined
      }
      onMove={
        rowActions && !entry.isDraft
          ? (destinationFolderId) => rowActions.onMoveNote(entry.id, destinationFolderId)
          : undefined
      }
      onCreateFolder={
        rowActions && !entry.isDraft ? rowActions.onCreateFolder : undefined
      }
      onChangeIcon={
        rowActions && !entry.isDraft
          ? (emoji) => rowActions.onChangeNoteIcon(entry.id, emoji)
          : undefined
      }
    />
  );
}

function ResourceRow({
  resource,
  level,
  onResourceClick,
  rowActions,
}: {
  resource: VaultResource;
  level: number;
  onResourceClick?(resource: VaultResource): void;
  rowActions?: SidebarRowActions;
}) {
  const isEditing = rowActions?.editingId === resource.id;

  return (
    <ResourceEntry
      resource={resource}
      level={level}
      // Same rename/navigate conflict guard as PageEntry/FolderEntry above
      // — Resource.tsx's own isClickable check already excludes edit mode,
      // this just avoids passing a stale click target while renaming.
      onClick={isEditing ? undefined : onResourceClick}
      isEditing={isEditing}
      onTitleCommit={
        rowActions
          ? (value) => rowActions.onResourceTitleCommit(resource.id, value)
          : undefined
      }
      onTitleEditingEnd={rowActions ? () => rowActions.onRenameEnd() : undefined}
      menuItems={rowActions ? buildResourceSidebarMenu() : undefined}
      menuOpen={rowActions?.openMenuId === resource.id}
      onMenuOpenChange={
        rowActions
          ? (open) => (open ? rowActions.onOpenMenu(resource.id) : rowActions.onCloseMenu())
          : undefined
      }
      onMenuSelect={
        rowActions
          ? (id) => {
              if (id === 'rename') {
                rowActions.onStartRename(resource.id);
              } else if (id === 'archive') {
                rowActions.onArchiveResource(resource.id);
              }
            }
          : undefined
      }
      moveDestinations={rowActions ? rowActions.resourceMoveDestinations : undefined}
      onMove={
        rowActions
          ? (destinationFolderId) => rowActions.onMoveResource(resource.id, destinationFolderId)
          : undefined
      }
      onCreateFolder={rowActions ? rowActions.onCreateFolder : undefined}
    />
  );
}

export function FolderTree({
  query,
  membershipSelector,
  workspace,
  parentId,
  level,
  onPageClick,
  onDraftPageClick,
  onFolderClick,
  onResourceClick,
  onCreateNote,
  pendingNewFolder,
  onCommitNewFolder,
  onCancelNewFolder,
  rowActions,
  resolveWikiLink,
  resolveTag,
}: FolderTreeProps) {
  // Get all folders that belong to the current parent. Root-level: ADR-023's
  // MembershipSelector is the single owner of "is this folder part of
  // Workspace" (formerly query.getVisibleRootFolders() here, and
  // independently query.getRootFolders() unfiltered in
  // toCollectionPageModel's Workspace branch — the two-definition bug
  // ADR-023 exists to close). Nested: no Workspace/system-folder membership
  // question applies one layer below the root, but dot-prefixed names are
  // still hidden from the UI at every depth — MembershipSelector.
  // getVisibleChildFolders() is the nested-level counterpart to
  // getWorkspaceFolders' root-level dot-hiding, wrapping the same
  // query.getChildFolders() structural source.
  const rootFolders =
    parentId === null
      ? membershipSelector.getWorkspaceFolders()
      : membershipSelector.getVisibleChildFolders(parentId);

  // Only meaningful at the true root — a nested folder's own pages are
  // already rendered via getNotesChildPages(folder.id) below, per folder.
  // ADR-020 (M3 amendment): sidebar membership includes draft-only pages
  // alongside durable ones — the sidebar always reflects what's
  // currently being edited. Unbounded draft accumulation is prevented
  // one layer down, at creation time (PageOperations.openDraft/
  // openAtPath's findReusableDraftId) — at most one empty draft of a
  // given type is ever open at once, so there's never more than one
  // "New Note"-placeholder row to show here.
  //
  // ADR-023: narrowed to Notes membership (page.type === 'note'), not just
  // folderId — this is the fix for a Daily Note draft (folderId: null
  // before its month folder exists) rendering here as if it were a Note.
  // Daily Notes membership is a different, identity-driven question
  // DailyNotesList now asks separately, through the same MembershipSelector.
  const rootPages = parentId === null ? membershipSelector.getNotesChildPages(null) : [];

  // Same "only meaningful at the true root" shape as rootPages above — a
  // nested folder's own resources are rendered via getVisibleChildResources
  // below, per folder. Rendered as its own block, after root pages, not
  // interleaved with them — matches how folders and pages themselves are
  // already two separate, non-interleaved blocks rather than one
  // alphabetically-merged list.
  const rootResources = parentId === null ? membershipSelector.getRootResources() : [];

  const isCreatingHere =
    pendingNewFolder !== null && pendingNewFolder.parentId === parentId;

  return (
    <>
      {isCreatingHere && (
        <NewFolderRow
          level={level}
          onCommit={(name) => onCommitNewFolder(name, parentId)}
          onCancel={onCancelNewFolder}
        />
      )}
      {/* Render every child folder. */}
      {rootFolders.map((folder) => {
        // Every page that should currently be shown as a child of this
        // folder — durable and draft-only alike (ADR-020), narrowed to
        // Notes membership (ADR-023); see the rootPages comment above for
        // both why draft accumulation isn't a concern here and why the
        // narrowing is necessary.
        const childPages = membershipSelector.getNotesChildPages(folder.id);
        const childResources = membershipSelector.getVisibleChildResources(folder.id);
        const subFolders = membershipSelector.getVisibleChildFolders(folder.id);
        // Checks if the folder is empty
        const isEmpty =
          subFolders.length === 0 &&
          childPages.length === 0 &&
          childResources.length === 0;
        // Empty folders default to collapsed rather than Workspace's normal
        // expanded-by-default state, since there's nothing to reveal.
        const isExpanded = isEmpty ? false : workspace.isFolderExpanded(folder.id);
        const isEditingFolder = rowActions?.editingId === folder.id;
        const folderLabel = getFolderDisplayLabel(folder);
        // Same "blank, not the literal generated string" rule the page
        // header (toResourcePageModel) applies to Notes — an untitled
        // folder's rename session starts from an empty field so
        // EditableText's own placeholder renders, rather than seeding the
        // input with "Untitled".
        const hasGeneratedFolderName = isAutoGeneratedName(folder.name);
        const folderEditingValue = hasGeneratedFolderName ? '' : folder.name;

        return (
          <Fragment key={folder.id}>
            {/* Render the current folder */}
            <FolderEntry
              title={isEditingFolder ? folderEditingValue : folderLabel.text}
              titlePlaceholder={
                isEditingFolder && hasGeneratedFolderName
                  ? getFolderTitlePlaceholder()
                  : undefined
              }
              titleStyle={getPageDisplayLabelStyle(folderLabel)}
              emoji={folder.metadata.icon}
              level={level}
              isEmpty={isEmpty}
              selected={workspace.activeFolderId === folder.id}
              isExpanded={isExpanded}
              onExpandToggle={() => workspace.toggleFolderExpanded(folder.id)}
              // Same rename/navigate conflict guard as PageEntry above.
              onClick={isEditingFolder ? undefined : () => onFolderClick(folder)}
              onAddClick={() => onCreateNote(folder.id)}
              isEditing={isEditingFolder}
              onTitleCommit={
                rowActions
                  ? (value) => rowActions.onFolderTitleCommit(folder.id, value)
                  : undefined
              }
              onTitleEdit={
                rowActions ? (value) => rowActions.onFolderTitleEdit(folder.id, value) : undefined
              }
              onTitleFlush={
                rowActions ? () => rowActions.onFolderTitleFlush(folder.id) : undefined
              }
              onTitleCancel={
                rowActions ? () => rowActions.onFolderTitleCancel(folder.id) : undefined
              }
              onTitleEditingEnd={rowActions ? () => rowActions.onRenameEnd() : undefined}
              menuItems={
                rowActions
                  ? buildFolderSidebarMenu(folder.metadata.status, folder.metadata.favorite)
                  : undefined
              }
              menuOpen={rowActions?.openMenuId === folder.id}
              onMenuOpenChange={
                rowActions
                  ? (open) => (open ? rowActions.onOpenMenu(folder.id) : rowActions.onCloseMenu())
                  : undefined
              }
              onMenuSelect={
                rowActions
                  ? (id) => {
                      if (id === 'rename') {
                        rowActions.onStartRename(folder.id);
                      } else if (id === 'toggle-favorite') {
                        rowActions.onToggleFavoriteFolder(
                          folder.id,
                          folder.metadata.favorite
                        );
                      } else if (id === 'archive') {
                        rowActions.onArchiveFolder(folder.id);
                      }
                    }
                  : undefined
              }
              moveDestinations={
                rowActions ? rowActions.getFolderMoveDestinations(folder.id) : undefined
              }
              onMove={
                rowActions
                  ? (destinationFolderId) => rowActions.onMoveFolder(folder.id, destinationFolderId)
                  : undefined
              }
              onCreateFolder={rowActions ? rowActions.onCreateFolder : undefined}
              onChangeIcon={
                rowActions
                  ? (emoji) => rowActions.onChangeFolderIcon(folder.id, emoji)
                  : undefined
              }
            />
            {/* Completes the existing Workspace.isFolderExpanded capability
                (ADR-021) — a collapsed folder's pages and subfolders render
                nothing, rather than only rotating the caret. */}
            {isExpanded && (
              <>
                {/* Render all pages inside this folder */}
                {childPages.map((entry) => (
                  <PageEntry
                    key={entry.id}
                    entry={entry}
                    level={level + 1}
                    workspace={workspace}
                    onPageClick={onPageClick}
                    onDraftPageClick={onDraftPageClick}
                    rowActions={rowActions}
                    resolveWikiLink={resolveWikiLink}
                    resolveTag={resolveTag}
                  />
                ))}
                {/* Render all resources (image/pdf) inside this folder,
                    after its pages — its own non-interleaved block, same
                    convention as pages vs. subfolders. */}
                {childResources.map((resource) => (
                  <ResourceRow
                    key={resource.id}
                    resource={resource}
                    level={level + 1}
                    onResourceClick={onResourceClick}
                    rowActions={rowActions}
                  />
                ))}
                {/* Render this folder's child folders.
                    This is the recursive call.
                    Every child folder repeats this exact process. */}
                <FolderTree
                  query={query}
                  membershipSelector={membershipSelector}
                  workspace={workspace}
                  parentId={folder.id}
                  level={level + 1}
                  onPageClick={onPageClick}
                  onDraftPageClick={onDraftPageClick}
                  onFolderClick={onFolderClick}
                  onResourceClick={onResourceClick}
                  onCreateNote={onCreateNote}
                  pendingNewFolder={pendingNewFolder}
                  onCommitNewFolder={onCommitNewFolder}
                  onCancelNewFolder={onCancelNewFolder}
                  rowActions={rowActions}
                  resolveWikiLink={resolveWikiLink}
                  resolveTag={resolveTag}
                />
              </>
            )}
          </Fragment>
        );
      })}
      {/* Render root-level pages, at the same indentation as root
          folders — they aren't nested under anything. */}
      {rootPages.map((entry) => (
        <PageEntry
          key={entry.id}
          entry={entry}
          level={level}
          workspace={workspace}
          onPageClick={onPageClick}
          onDraftPageClick={onDraftPageClick}
          rowActions={rowActions}
          resolveWikiLink={resolveWikiLink}
          resolveTag={resolveTag}
        />
      ))}
      {/* Render root-level resources, after root pages — same
          non-interleaved-block convention as everywhere else in this tree. */}
      {rootResources.map((resource) => (
        <ResourceRow
          key={resource.id}
          resource={resource}
          level={level}
          onResourceClick={onResourceClick}
          rowActions={rowActions}
        />
      ))}
    </>
  );
}
