// React
import { Fragment } from 'react/jsx-runtime';
// Components
import { Folder as FolderEntry } from './Folder';
import { Note as NoteEntry } from './Note';
import { Resource as ResourceEntry } from './Resource';
import { NewFolderRow } from './NewFolderRow';
import { ShowMoreEntry } from '@components/entry/ShowMoreEntry';
import { buildResourceActionMenu } from '@core/presentation/resourceActions/buildResourceActionMenu';
import { buildPageMenuHandlers } from '../helpers/buildPageMenuHandlers';
import { SORT_MENU_ID_PREFIX } from '@core/presentation/resourceActions/folderSortAction';
import { buildFolderMenuHandlers } from '../helpers/buildFolderMenuHandlers';
import { levelKindOrder, sortSidebarFolders, sortSidebarPages } from './sidebarSort';
import {
  DEFAULT_SIDEBAR_SORT,
  isSidebarSortKey,
  type SidebarSort,
} from '@core/properties/sidebarSort';
import { buildAssetMenuHandlers } from '../helpers/buildAssetMenuHandlers';
import { testIds } from '@shared/testing/selectors';
import type { OverflowMenuItemConfig } from '@components/menu/OverflowMenu';
// Models
import type { Folder } from '@core/vault/models';
import type { VaultResource } from '@core/vault/models/VaultResource';
// Presentation
import {
  getPageDisplayLabel,
  getPageDisplayLabelStyle,
} from '@core/presentation/getPageDisplayLabel';
import { getFolderDisplayLabel } from '@core/presentation/getFolderDisplayLabel';
import {
  getFolderTitlePlaceholder,
  getPageTitlePlaceholder,
} from '@core/presentation/PageDisplayPlaceholders';
import { isAutoGeneratedName } from '@core/shared/naming/AutoGeneratedName';
import type { LocationPathFormat } from '@core/presentation/getLocationPathRepresentations';
import type { PickerListItem } from '@components/picker-list/PickerList.types';
// Queries
import type { VaultQuery } from '@core/vault/queries/VaultQuery';
import type { Workspace } from '@core/workspace/Workspace';
import type { EffectivePage } from '@core/application/page/EffectivePageState';
import type { MembershipSelector } from '@core/application/membership/MembershipSelector';
import type { ResolveTag, ResolveWikiLink } from '@features/markdown/editor/MarkdownEditor';
import type { ResolvePageEmbed } from '@features/markdown/render/blocks/pageEmbedResolution';

/** A folder shows this many of its own notes and files; the rest sit behind its "N more" row. */
export const SIDEBAR_FOLDER_ITEM_LIMIT = 10;

/** The key the vault root's own notes/files use in `expandedFolders` (a real folder id is never this). */
export const ROOT_FOLDER_CAP_KEY = '__root__';

/**
 * Where a folder or note sits in its parent's list, in the order that list is drawn (the root: folders,
 * notes, files; a nested level: notes, files, subfolders) — what the 10-item cap counts against.
 * -1 when the item isn't in that list.
 */
export function getLevelIndex(
  membershipSelector: MembershipSelector,
  parentId: string | null,
  kind: 'folder' | 'page',
  id: string,
  sort?: SidebarSort
): number {
  const folders = sortSidebarFolders(
    parentId === null
      ? membershipSelector.getWorkspaceFolders()
      : membershipSelector.getVisibleChildFolders(parentId),
    sort
  );
  const pages = sortSidebarPages(membershipSelector.getNotesChildPages(parentId), sort);
  const resourceCount =
    parentId === null
      ? membershipSelector.getRootResources().length
      : membershipSelector.getVisibleChildResources(parentId).length;

  if (kind === 'folder') {
    const index = folders.findIndex((folder) => folder.id === id);
    return index < 0 ? -1 : parentId === null ? index : pages.length + resourceCount + index;
  }
  const index = pages.findIndex((entry) => entry.id === id);
  return index < 0 ? -1 : parentId === null ? folders.length + index : index;
}

export interface PendingNewFolder {
  // The parent under which a not-yet-persisted folder is being named.
  // null means the vault root.
  readonly parentId: string | null;
}

/**
 * Single owner of "which row's overflow menu/rename session is active,"
 * supplied by the caller (Sidebar.Notes.tsx) so it's shared across every
 * row FolderTree recurses through — the mechanism that guarantees only
 * one menu is ever open at a time, and threads every menu action back to
 * PageOperations/FolderOperations, the facades that already own rename/
 * archive/delete (no new write path is introduced by any handler here).
 * Optional so every existing FolderTree caller/test that doesn't wire row
 * actions keeps rendering the plain, unwired overflow button it always
 * has.
 */
/**
 * The subset of `SidebarRowActions` a Note row actually uses — split out
 * so a second, independent context that renders Note rows outside the
 * Notes-sidebar folder tree (today: the Tags sidebar's expanded-tag note
 * list) can supply exactly this, and nothing folder/resource-shaped, to
 * the exact same `PageEntry`/`Note` component this file already renders
 * — rather than either faking out unused folder/resource fields or a
 * second, parallel note-row implementation. `SidebarRowActions` below
 * extends this unchanged for every existing caller (FolderTree itself,
 * Sidebar.Notes.tsx, FavoriteList).
 */
export interface NoteRowActions {
  openMenuId: string | null;
  onOpenMenu(id: string): void;
  onCloseMenu(): void;

  editingId: string | null;
  onStartRename(id: string): void;
  onRenameEnd(): void;

  /** Continuous-commit channel (PageOperations.commitTitle), persisted notes only. */
  onNoteTitleEdit(pageId: string, value: string): void;
  onNoteTitleFlush(pageId: string): void;
  onNoteTitleCancel(pageId: string): void;
  /**
   * Discrete Enter/blur-changed commit for a persisted note — a
   * synchronous canRename() pre-check only (PageOperations.canRename()),
   * returning false to reject a colliding title. Unlike a draft's commit,
   * this never itself persists: the continuous channel above already does
   * that, and PageOperations.rename() (which the continuous channel calls)
   * re-validates the same collision internally, so a duplicate can never
   * actually be written even if this pre-check and the continuous save
   * race each other.
   */
  onNoteTitleCommit(pageId: string, value: string): void | boolean;
  /** Discrete commit (PageOperations.updateDraftTitle), draft notes only. */
  onDraftTitleCommit(pageId: string, value: string): void | boolean;
  /**
   * No onDeleteNote here — the sidebar menu config
   * (noteSidebarMenu.config.ts) never includes a 'delete' item
   * (deletion-UX product decision: permanent Delete is withdrawn from
   * every ordinary workspace resource, and this row never renders an
   * archived one), so there is no dispatch target for it.
   */
  onArchiveNote(pageId: string): void;
  /** ADR-028 — a raw filesystem copy, see PageOperations.duplicate(). */
  onDuplicateNote(pageId: string): void;
  /**
   * Same PageOperations.updateMetadata({ favorite }) call the topbar's
   * favorite control and the Daily Notes sidebar's onToggleFavoriteNote
   * both dispatch to — one operation, shared across every entry point.
   * Takes the row's current favorite state (from its EffectivePage entry)
   * rather than looking it up separately.
   */
  onToggleFavoriteNote(pageId: string, isFavorite: boolean): void;
  /** PageOperations.updateMetadata({ icon }) — sidebar Change icon action. */
  onChangeNoteIcon(pageId: string, emoji: string | null): void;
  /**
   * Same Move flow as ResourceTopBarActions' (buildMoveDestinationItems.ts
   * + PageOperations.move) — a single destination list, since which
   * folders a note may move into doesn't depend on the note itself,
   * unlike a folder's own list (getFolderMoveDestinations below).
   */
  noteMoveDestinations: PickerListItem[];
  onMoveNote(pageId: string, destinationFolderId: string | null): void;
  /**
   * Shared by every Move entry point in the sidebar (note and folder
   * rows alike) — the same FolderOperations.create() the "+" button
   * already uses, just invoked from the Move picker's own "Create ..."
   * row instead. See MoveDestinationPicker's own doc comment for the
   * full create-then-select-then-close flow.
   */
  onCreateFolder(name: string): Promise<string>;
  /**
   * Location-actions pipeline, page-scoped (Note and Daily Note — both a
   * `Page`, see `getLocationPathRepresentations.ts`'s `LocationEntityKind`
   * doc comment). Read-only OS interaction, not a `PageOperations`
   * capability: no Gate/Vault write path is involved. Daily Note rows
   * dispatch through this same pair via their own `SidebarRowActions`
   * instance (Sidebar.DailyNotes.tsx), not a separate
   * onRevealDailyNoteInFinder — one Page-shaped implementation, not two.
   */
  onRevealPageInFinder(pageId: string): void;
  /** Copies one of the three location representations — see onRevealPageInFinder above. */
  onCopyPagePath(pageId: string, format: LocationPathFormat): void;
}

export interface SidebarRowActions extends NoteRowActions {
  /**
   * Discrete Enter/blur-changed commit for a folder — a synchronous
   * canRename() pre-check only (FolderOperations.canRename()), same shape
   * and reasoning as onNoteTitleCommit above: the continuous channel below
   * still does the actual persisting.
   */
  onFolderTitleCommit(folderId: string, value: string): void | boolean;
  /** Continuous-commit channel (FolderOperations.commitName), same shape as a persisted note's title. */
  onFolderTitleEdit(folderId: string, value: string): void;
  onFolderTitleFlush(folderId: string): void;
  onFolderTitleCancel(folderId: string): void;
  onArchiveFolder(folderId: string): void;
  /**
   * FolderOperations.updateMetadata({ favorite }) — the folder-scoped
   * counterpart to onToggleFavoriteNote above, same shared-call shape.
   * Takes the row's current favorite state (from `folder.metadata.favorite`)
   * rather than looking it up separately.
   */
  onToggleFavoriteFolder(folderId: string, isFavorite: boolean): void;
  /** FolderOperations.updateMetadata({ icon }) — sidebar Change icon action. */
  onChangeFolderIcon(folderId: string, emoji: string | null): void;
  /**
   * Per-folder — excludes that folder (and its own descendants) from its
   * own destination list, same as buildMoveDestinationItems.ts's
   * excludeFolderId does for the topbar's folder Move.
   */
  getFolderMoveDestinations(folderId: string): PickerListItem[];
  onMoveFolder(folderId: string, destinationFolderId: string | null): void;

  /**
   * Discrete-commit-only, mirroring a draft Note's onDraftTitleCommit shape
   * (no continuous channel — ResourceOperations.renameResource() is a
   * single one-shot Gate call, not a debounced autosave). Never returns
   * `false`: unlike onNoteTitleCommit/onFolderTitleCommit, a resource
   * rename never synchronously rejects a collision — it always dispatches,
   * relying entirely on MoveService.resolveResourceRenameDestination's
   * existing auto-suffix behavior, per the approved Resource mutation
   * design (no reject-on-collision rule for resources).
   */
  onResourceTitleCommit(resourceId: string, value: string): void;
  /**
   * ResourceOperations.archiveResource() — no confirmation dialog, same
   * shape as onArchiveNote (a resource, like a page, is always a single
   * leaf with no descendants, so it never needs the non-empty-folder
   * confirmation onArchiveFolder gates behind).
   */
  onArchiveResource(resourceId: string): void;
  /**
   * Same Move flow as noteMoveDestinations above — one shared destination
   * list, since which folders a resource may move into doesn't depend on
   * the resource itself, same reasoning noteMoveDestinations already
   * applies. Unlike noteMoveDestinations, this list also surfaces the
   * managed Assets/ folder as a selectable destination (normally hidden
   * from Note/Folder's own picker via MembershipSelector.
   * isAssetsStorageFolder) — moving a resource *into* Assets/ is one of
   * the required Resource Move destinations, per the approved design.
   */
  resourceMoveDestinations: PickerListItem[];
  onMoveResource(resourceId: string, destinationFolderId: string | null): void;
  /**
   * Location-actions pipeline (`core/presentation/
   * getLocationPathRepresentations.ts`) — reveals the resource's real file
   * in the native OS file manager. Read-only OS interaction, not a
   * ResourceOperations capability: no Gate/Vault write path is involved.
   * Shared by both resource kinds (image/pdf) and both surfaces the
   * resource menu renders in (this sidebar row, `AssetsCollectionBody`).
   */
  onRevealResourceInFinder(resourceId: string): void;
  /** Copies one of the three location representations — see onRevealResourceInFinder above. */
  onCopyResourcePath(resourceId: string, format: LocationPathFormat): void;
  /**
   * Exports a copy of an image resource's original file to a user-chosen
   * destination via the native Save dialog (`downloadResource.ts`) — read-only
   * from the Vault's perspective (reads the source file, never touches
   * `VaultFileSystem` or creates a new `VaultResource`), so it carries the
   * same no-Gate-involvement reasoning as onRevealResourceInFinder above.
   * Image-only — the canonical asset actions only list this item for
   * `resource.kind === 'image'`, so a pdf row's menu never dispatches here.
   */
  onDownloadResource(resourceId: string): void;
  /** Location-actions pipeline, folder-scoped — no 'as-markdown' format ever reaches this (the menu never offers it for a folder). */
  onRevealFolderInFinder(folderId: string): void;
  /** Copies one of the two location representations available for a folder — see onRevealFolderInFinder above. */
  onCopyFolderPath(folderId: string, format: LocationPathFormat): void;
}

interface FolderTreeProps {
  // Folders only — folders have no draft concept (ADR-017 is scoped to
  // pages). Still threaded through (not read directly by this component
  // beyond passing it to the recursive call below) because the recursive
  // <FolderTree> instance needs it.
  query: VaultQuery;
  // ADR-023: the single owner of "is this folder part of Workspace" — used
  // for the true root's folder list (getWorkspaceFolders()) and, one layer
  // down, for dot-prefixed-name hiding via getVisibleChildFolders() — a
  // folder already inside a non-reserved folder is never itself a
  // reserved folder (nothing to classify one layer down for *that*
  // question), but a dot-prefixed name still needs hiding at every depth.
  membershipSelector: MembershipSelector;
  workspace: Workspace;
  // The folder whose children we're currently rendering.
  // null means "start from the root".
  parentId: string | null;
  // Used to indent nested folders.
  level: number;
  /**
   * Invoked when a durable page entry is selected.
   */
  onPageClick(pageId: string): void;
  /**
   * Invoked when a draft-only page entry is selected — distinct from
   * onPageClick because reopening a draft is a re-select
   * (Workspace.openPage), not PageOperations.open() (which requires a
   * Vault entry and would throw for a draft).
   */
  onDraftPageClick(pageId: string): void;
  /**
   * Invoked when a folder entry is selected.
   */
  onFolderClick(folder: Folder): void;
  /**
   * Invoked when a resource entry (image or pdf) is clicked — the caller
   * (Sidebar.tsx) decides which overlay to open based on `resource.kind`.
   */
  onResourceClick?(resource: VaultResource): void;
  /**
   * Invoked when a folder row's "+" action is clicked — opens a new draft
   * note scoped to that folder (PageOperations.openDraft({ folderId })).
   */
  onCreateNote(folderId: string): void;
  /**
   * At most one folder-creation row is active anywhere in the tree at a
   * time. Every recursive level checks whether it owns this pending
   * folder's parentId, so root-level and nested creation share the exact
   * same mechanism rather than the root being special-cased.
   */
  pendingNewFolder: PendingNewFolder | null;
  onCommitNewFolder(name: string, parentId: string | null): void | boolean;
  onCancelNewFolder(): void;
  /** Overflow-menu/rename wiring — see SidebarRowActions. */
  rowActions?: SidebarRowActions;
  /** Same injected resolution boundary the page editor uses — see Note's own prop doc comment. */
  resolveWikiLink?: ResolveWikiLink;
  resolveTag?: ResolveTag;
  resolveEmbed?: ResolvePageEmbed;
  /** Folders (by id, or ROOT_FOLDER_CAP_KEY) whose "N more" row was clicked — shown in full. Session-only; the owner decides its lifetime. */
  expandedFolders?: readonly string[];
  /** Called when a folder's "N more" / "Show less" row is clicked. */
  onToggleFolderCap?(key: string): void;
  /**
   * The order the user chose for a folder's children in the sidebar (Sort by in its menu), or
   * undefined for the default. Persisted by the caller; the root level has no sort.
   */
  getFolderSort?(folderId: string): SidebarSort | undefined;
  /** Called when a Sort by row in a folder's menu is picked. */
  onFolderSortChange?(folderId: string, sort: SidebarSort): void;
}

export interface PageEntryProps {
  entry: EffectivePage;
  level: number;
  workspace: Workspace;
  onPageClick(pageId: string): void;
  onDraftPageClick(pageId: string): void;
  /**
   * Narrowed to `NoteRowActions` (not the full `SidebarRowActions`) —
   * this component only ever reads the Note-shaped subset, so a caller
   * with no folders/resources of its own (the Tags sidebar's expanded
   * note list) can supply exactly that, nothing more.
   */
  rowActions?: NoteRowActions;
  resolveWikiLink?: ResolveWikiLink;
  resolveTag?: ResolveTag;
  resolveEmbed?: ResolvePageEmbed;
  /**
   * Spliced into the standard note menu (the Note sidebar menu's items),
   * immediately above "Reveal in Finder" — see insertBeforeRevealInFinder
   * below — for an action that exists only in one calling context, not
   * every Note row everywhere (today: the Tags sidebar's "Reveal in
   * Clutter"). Omitted everywhere else, so the Notes sidebar's own menu
   * is unaffected. `onExtraMenuSelect` only ever receives ids from this
   * list — every id the canonical Note actions produce is still
   * handled internally, unchanged.
   */
  extraMenuItems?: readonly OverflowMenuItemConfig[];
  onExtraMenuSelect?(id: string): void;
  /**
   * Whether this row shows the "currently active page" highlight when
   * `workspace.activePageId` matches it — true (the Notes sidebar's own
   * existing behavior) unless a caller explicitly opts out. The Tags
   * sidebar's expanded-tag note entry sets this `false`: a tag's note
   * entry represents note-level membership, not "this is the open
   * page," and the same note's sibling context entries (a different
   * row entirely) are a different, far more common way to open it from
   * here — highlighting the note entry as a side effect of opening it
   * via one of ITS OWN context entries read as an unrelated row
   * lighting up for no reason the user did to that row specifically.
   */
  highlightActive?: boolean;
}

/**
 * Splices `extraItems` into `standardItems` immediately before the
 * "Reveal in Finder" item (buildLocationActionMenuItems' `reveal-in-finder`
 * id) — e.g. the Tags sidebar's "Reveal in Clutter", which reads
 * naturally grouped with the menu's other location/navigation actions
 * rather than tacked on at the very end, after Archive. Falls back to
 * appending at the end if that item is ever absent (a draft's empty
 * menu, or a future standard-menu change), so this never silently drops
 * `extraItems`.
 */
function insertBeforeRevealInFinder(
  standardItems: OverflowMenuItemConfig[],
  extraItems: readonly OverflowMenuItemConfig[] | undefined
): OverflowMenuItemConfig[] {
  if (!extraItems || extraItems.length === 0) {
    return standardItems;
  }

  const revealInFinderIndex = standardItems.findIndex((item) => item.id === 'reveal-in-finder');
  const revealInFinder = standardItems[revealInFinderIndex];

  if (!revealInFinder) {
    return [...standardItems, ...extraItems];
  }

  // "Reveal in Finder" opens the location group's divider; the extras now
  // lead that group, so the divider moves to the first of them.
  const groupDivider = revealInFinder.separatorBefore;

  return [
    ...standardItems.slice(0, revealInFinderIndex),
    ...extraItems.map((item, index) =>
      index === 0 ? { ...item, separatorBefore: groupDivider } : item
    ),
    { ...revealInFinder, separatorBefore: false },
    ...standardItems.slice(revealInFinderIndex + 1),
  ];
}

/**
 * The exact same Note row FolderTree renders for every note in the Notes
 * sidebar — exported so a second context that lists `EffectivePage`s
 * outside the folder tree (today: the Tags sidebar's expanded-tag note
 * list, see `renderTags.tsx`) renders identically: same layout, selection,
 * click behavior, overflow menu, rename, archive, favorite, move, and
 * reveal/copy-path actions — rather than a second, reduced implementation.
 */
export function PageEntry({
  entry,
  level,
  workspace,
  onPageClick,
  onDraftPageClick,
  rowActions,
  resolveWikiLink,
  resolveTag,
  resolveEmbed,
  extraMenuItems,
  onExtraMenuSelect,
  highlightActive = true,
}: PageEntryProps) {
  const label = getPageDisplayLabel(entry);
  const isEditing = rowActions?.editingId === entry.id;
  const hasGeneratedName = isAutoGeneratedName(entry.name);
  const noteEditingValue = hasGeneratedName ? '' : entry.name;

  return (
    <NoteEntry
      data-testid={testIds.sidebar.noteItem(entry.id)}
      title={isEditing ? noteEditingValue : label.text}
      titlePlaceholder={
        isEditing && hasGeneratedName ? getPageTitlePlaceholder(entry.type) : undefined
      }
      titleStyle={getPageDisplayLabelStyle(label)}
      emoji={entry.icon}
      resolveWikiLink={resolveWikiLink}
      resolveTag={resolveTag}
      resolveEmbed={resolveEmbed}
      level={level}
      selected={highlightActive && workspace.activePageId === entry.id}
      // A row mid-rename must not also navigate on click — EditableText's
      // contenteditable surface isn't one of Entry's recognized
      // interactive-descendant tags, so leaving onClick wired here would
      // fire row selection on every click into the field.
      onClick={
        isEditing
          ? undefined
          : () => (entry.isDraft ? onDraftPageClick(entry.id) : onPageClick(entry.id))
      }
      isEditing={isEditing}
      onTitleEdit={
        !entry.isDraft && rowActions
          ? (value) => rowActions.onNoteTitleEdit(entry.id, value)
          : undefined
      }
      onTitleFlush={
        !entry.isDraft && rowActions ? () => rowActions.onNoteTitleFlush(entry.id) : undefined
      }
      onTitleCancel={
        !entry.isDraft && rowActions ? () => rowActions.onNoteTitleCancel(entry.id) : undefined
      }
      onTitleCommit={
        rowActions
          ? (value) =>
              entry.isDraft
                ? rowActions.onDraftTitleCommit(entry.id, value)
                : rowActions.onNoteTitleCommit(entry.id, value)
          : undefined
      }
      onTitleEditingEnd={rowActions ? () => rowActions.onRenameEnd() : undefined}
      menuItems={
        rowActions
          ? insertBeforeRevealInFinder(
              buildResourceActionMenu(
                'note',
                { isDraft: entry.isDraft, isFavorite: entry.favorite, status: 'active' },
                'sidebar'
              ),
              extraMenuItems
            )
          : undefined
      }
      menuOpen={rowActions?.openMenuId === entry.id}
      onMenuOpenChange={
        rowActions
          ? (open) => (open ? rowActions.onOpenMenu(entry.id) : rowActions.onCloseMenu())
          : undefined
      }
      onMenuSelect={
        rowActions
          ? (id) => {
              const handler = buildPageMenuHandlers(rowActions, entry.id, entry.favorite)[id];

              if (handler) {
                handler();
              } else {
                onExtraMenuSelect?.(id);
              }
            }
          : undefined
      }
      moveDestinations={
        rowActions && !entry.isDraft ? rowActions.noteMoveDestinations : undefined
      }
      onMove={
        rowActions && !entry.isDraft
          ? (destinationFolderId) => rowActions.onMoveNote(entry.id, destinationFolderId)
          : undefined
      }
      onCreateFolder={
        rowActions && !entry.isDraft ? rowActions.onCreateFolder : undefined
      }
      onChangeIcon={
        rowActions && !entry.isDraft
          ? (emoji) => rowActions.onChangeNoteIcon(entry.id, emoji)
          : undefined
      }
    />
  );
}

function ResourceRow({
  resource,
  level,
  onResourceClick,
  rowActions,
}: {
  resource: VaultResource;
  level: number;
  onResourceClick?(resource: VaultResource): void;
  rowActions?: SidebarRowActions;
}) {
  const isEditing = rowActions?.editingId === resource.id;

  return (
    <ResourceEntry
      resource={resource}
      level={level}
      // Same rename/navigate conflict guard as PageEntry/FolderEntry above
      // — Resource.tsx's own isClickable check already excludes edit mode,
      // this just avoids passing a stale click target while renaming.
      onClick={isEditing ? undefined : onResourceClick}
      isEditing={isEditing}
      onTitleCommit={
        rowActions
          ? (value) => rowActions.onResourceTitleCommit(resource.id, value)
          : undefined
      }
      onTitleEditingEnd={rowActions ? () => rowActions.onRenameEnd() : undefined}
      menuItems={
        rowActions
          ? buildResourceActionMenu('asset', { assetKind: resource.kind, status: 'active' }, 'sidebar')
          : undefined
      }
      menuOpen={rowActions?.openMenuId === resource.id}
      onMenuOpenChange={
        rowActions
          ? (open) => (open ? rowActions.onOpenMenu(resource.id) : rowActions.onCloseMenu())
          : undefined
      }
      onMenuSelect={
        rowActions
          ? (id) => buildAssetMenuHandlers(
              {
                onStartRename: rowActions.onStartRename,
                onArchiveResource: rowActions.onArchiveResource,
                onRevealResourceInFinder: rowActions.onRevealResourceInFinder,
                onCopyResourcePath: rowActions.onCopyResourcePath,
                onDownloadResource: rowActions.onDownloadResource,
              },
              resource.id
            )[id]?.()
          : undefined
      }
      moveDestinations={rowActions ? rowActions.resourceMoveDestinations : undefined}
      onMove={
        rowActions
          ? (destinationFolderId) => rowActions.onMoveResource(resource.id, destinationFolderId)
          : undefined
      }
      onCreateFolder={rowActions ? rowActions.onCreateFolder : undefined}
    />
  );
}

export function FolderTree({
  query,
  membershipSelector,
  workspace,
  parentId,
  level,
  onPageClick,
  onDraftPageClick,
  onFolderClick,
  onResourceClick,
  onCreateNote,
  pendingNewFolder,
  onCommitNewFolder,
  onCancelNewFolder,
  rowActions,
  resolveWikiLink,
  resolveTag,
  resolveEmbed,
  expandedFolders = [],
  onToggleFolderCap,
  getFolderSort,
  onFolderSortChange,
}: FolderTreeProps) {
  // Get all folders that belong to the current parent. Root-level: ADR-023's
  // MembershipSelector is the single owner of "is this folder part of
  // Workspace" (formerly query.getVisibleRootFolders() here, and
  // independently query.getRootFolders() unfiltered in
  // toCollectionPageModel's Workspace branch — the two-definition bug
  // ADR-023 exists to close). Nested: no Workspace/system-folder membership
  // question applies one layer below the root, but dot-prefixed names are
  // still hidden from the UI at every depth — MembershipSelector.
  // getVisibleChildFolders() is the nested-level counterpart to
  // getWorkspaceFolders' root-level dot-hiding, wrapping the same
  // query.getChildFolders() structural source.
  // The order the user chose for this level in the sidebar (a nested level only — the root has no
  // Sort by); undefined keeps the default order.
  const levelSort = parentId === null ? undefined : getFolderSort?.(parentId);
  const rootFolders = sortSidebarFolders(
    parentId === null
      ? membershipSelector.getWorkspaceFolders()
      : membershipSelector.getVisibleChildFolders(parentId),
    levelSort
  );

  // Only meaningful at the true root — a nested folder's own pages are
  // already rendered via getNotesChildPages(folder.id) below, per folder.
  // ADR-020 (M3 amendment): sidebar membership includes draft-only pages
  // alongside durable ones — the sidebar always reflects what's
  // currently being edited. Unbounded draft accumulation is prevented
  // one layer down, at creation time (PageOperations.openDraft/
  // openAtPath's findReusableDraftId) — at most one empty draft of a
  // given type is ever open at once, so there's never more than one
  // "New Note"-placeholder row to show here.
  //
  // ADR-023: narrowed to Notes membership (page.type === 'note'), not just
  // folderId — this is the fix for a Daily Note draft (folderId: null
  // before its month folder exists) rendering here as if it were a Note.
  // Daily Notes membership is a different, identity-driven question
  // DailyNotesList now asks separately, through the same MembershipSelector.
  const rootPages = parentId === null ? membershipSelector.getNotesChildPages(null) : [];

  // Same "only meaningful at the true root" shape as rootPages above — a
  // nested folder's own resources are rendered via getVisibleChildResources
  // below, per folder. Rendered as its own block, after root pages, not
  // interleaved with them — matches how folders and pages themselves are
  // already two separate, non-interleaved blocks rather than one
  // alphabetically-merged list.
  const rootResources = parentId === null ? membershipSelector.getRootResources() : [];

  const isCreatingHere =
    pendingNewFolder !== null && pendingNewFolder.parentId === parentId;

  const renderFolder = (folder: Folder) => {
        // Every page that should currently be shown as a child of this
        // folder — durable and draft-only alike (ADR-020), narrowed to
        // Notes membership (ADR-023); see the rootPages comment above for
        // both why draft accumulation isn't a concern here and why the
        // narrowing is necessary.
        const childPages = membershipSelector.getNotesChildPages(folder.id);
        const childResources = membershipSelector.getVisibleChildResources(folder.id);
        const subFolders = membershipSelector.getVisibleChildFolders(folder.id);
        // Checks if the folder is empty
        const isEmpty =
          subFolders.length === 0 &&
          childPages.length === 0 &&
          childResources.length === 0;
        // Empty folders default to collapsed rather than Workspace's normal
        // expanded-by-default state, since there's nothing to reveal.
        const isExpanded = isEmpty ? false : workspace.isFolderExpanded(folder.id);
        const isEditingFolder = rowActions?.editingId === folder.id;
        const folderLabel = getFolderDisplayLabel(folder);
        // Same "blank, not the literal generated string" rule the page
        // header (toResourcePageModel) applies to Notes — an untitled
        // folder's rename session starts from an empty field so
        // EditableText's own placeholder renders, rather than seeding the
        // input with "Untitled".
        const hasGeneratedFolderName = isAutoGeneratedName(folder.name);
        const folderEditingValue = hasGeneratedFolderName ? '' : folder.name;

        return (
          <Fragment key={folder.id}>
            {/* Render the current folder */}
            <FolderEntry
              title={isEditingFolder ? folderEditingValue : folderLabel.text}
              titlePlaceholder={
                isEditingFolder && hasGeneratedFolderName
                  ? getFolderTitlePlaceholder()
                  : undefined
              }
              titleStyle={getPageDisplayLabelStyle(folderLabel)}
              emoji={folder.metadata.icon}
              level={level}
              isEmpty={isEmpty}
              selected={workspace.activeFolderId === folder.id}
              isExpanded={isExpanded}
              onExpandToggle={() => workspace.toggleFolderExpanded(folder.id)}
              // Same rename/navigate conflict guard as PageEntry above.
              onClick={isEditingFolder ? undefined : () => onFolderClick(folder)}
              onAddClick={() => onCreateNote(folder.id)}
              isEditing={isEditingFolder}
              onTitleCommit={
                rowActions
                  ? (value) => rowActions.onFolderTitleCommit(folder.id, value)
                  : undefined
              }
              onTitleEdit={
                rowActions ? (value) => rowActions.onFolderTitleEdit(folder.id, value) : undefined
              }
              onTitleFlush={
                rowActions ? () => rowActions.onFolderTitleFlush(folder.id) : undefined
              }
              onTitleCancel={
                rowActions ? () => rowActions.onFolderTitleCancel(folder.id) : undefined
              }
              onTitleEditingEnd={rowActions ? () => rowActions.onRenameEnd() : undefined}
              menuItems={
                rowActions
                  ? buildResourceActionMenu(
                      'folder',
                      {
                        status: folder.metadata.status,
                        isFavorite: folder.metadata.favorite,
                        sort: onFolderSortChange
                          ? (getFolderSort?.(folder.id) ?? DEFAULT_SIDEBAR_SORT)
                          : undefined,
                      },
                      'sidebar'
                    )
                  : undefined
              }
              menuOpen={rowActions?.openMenuId === folder.id}
              onMenuOpenChange={
                rowActions
                  ? (open) => (open ? rowActions.onOpenMenu(folder.id) : rowActions.onCloseMenu())
                  : undefined
              }
              onMenuSelect={
                rowActions
                  ? (id) => {
                      if (id.startsWith(SORT_MENU_ID_PREFIX)) {
                        const key = id.slice(SORT_MENU_ID_PREFIX.length);
                        if (isSidebarSortKey(key)) {
                          const current = getFolderSort?.(folder.id) ?? DEFAULT_SIDEBAR_SORT;
                          // Same rule as the collection views: re-picking the active key flips
                          // its direction; another key starts at its own default ('down').
                          onFolderSortChange?.(
                            folder.id,
                            current.key === key
                              ? { key, direction: current.direction === 'down' ? 'up' : 'down' }
                              : { key, direction: 'down' }
                          );
                        }
                      } else {
                        buildFolderMenuHandlers(
                          rowActions,
                          folder.id,
                          folder.metadata.favorite
                        )[id]?.();
                      }
                    }
                  : undefined
              }
              moveDestinations={
                rowActions ? rowActions.getFolderMoveDestinations(folder.id) : undefined
              }
              onMove={
                rowActions
                  ? (destinationFolderId) => rowActions.onMoveFolder(folder.id, destinationFolderId)
                  : undefined
              }
              onCreateFolder={rowActions ? rowActions.onCreateFolder : undefined}
              onChangeIcon={
                rowActions
                  ? (emoji) => rowActions.onChangeFolderIcon(folder.id, emoji)
                  : undefined
              }
            />
            {/* Completes the existing Workspace.isFolderExpanded capability
                (ADR-021) — a collapsed folder's pages and subfolders render
                nothing, rather than only rotating the caret. */}
            {isExpanded && (
                <FolderTree
                  query={query}
                  membershipSelector={membershipSelector}
                  workspace={workspace}
                  parentId={folder.id}
                  level={level + 1}
                  onPageClick={onPageClick}
                  onDraftPageClick={onDraftPageClick}
                  onFolderClick={onFolderClick}
                  onResourceClick={onResourceClick}
                  onCreateNote={onCreateNote}
                  pendingNewFolder={pendingNewFolder}
                  onCommitNewFolder={onCommitNewFolder}
                  onCancelNewFolder={onCancelNewFolder}
                  rowActions={rowActions}
                  resolveWikiLink={resolveWikiLink}
                  resolveTag={resolveTag}
                  resolveEmbed={resolveEmbed}
                  expandedFolders={expandedFolders}
                  onToggleFolderCap={onToggleFolderCap}
                  getFolderSort={getFolderSort}
                  onFolderSortChange={onFolderSortChange}
                />
            )}
          </Fragment>
        );
  };

  // This folder's own notes and files for a nested level — the root has its own (rootPages/
  // rootResources above). A nested level lists its notes, then files, then subfolders; the root
  // lists folders first, then notes, then files. Whatever the order, the level shows its first
  // SIDEBAR_FOLDER_ITEM_LIMIT items, then a "N more" / "Show less" row.
  const levelPages =
    parentId === null
      ? rootPages
      : sortSidebarPages(membershipSelector.getNotesChildPages(parentId), levelSort);
  const levelResources =
    parentId === null ? rootResources : membershipSelector.getVisibleChildResources(parentId);

  type LevelItem =
    | { kind: 'folder'; folder: Folder }
    | { kind: 'page'; entry: EffectivePage }
    | { kind: 'resource'; resource: VaultResource };
  const folderItems: LevelItem[] = rootFolders.map((folder) => ({ kind: 'folder', folder }));
  const pageItems: LevelItem[] = levelPages.map((entry) => ({ kind: 'page', entry }));
  const resourceItems: LevelItem[] = levelResources.map((resource) => ({
    kind: 'resource',
    resource,
  }));
  const itemsByKind = { folder: folderItems, page: pageItems, resource: resourceItems };
  const items = levelKindOrder(parentId === null, levelSort).flatMap((kind) => itemsByKind[kind]);

  const capKey = parentId ?? ROOT_FOLDER_CAP_KEY;
  const isCapExpanded = expandedFolders.includes(capKey);
  const visibleItems = isCapExpanded ? items : items.slice(0, SIDEBAR_FOLDER_ITEM_LIMIT);

  const renderItem = (item: LevelItem) => {
    if (item.kind === 'folder') {
      return renderFolder(item.folder);
    }
    if (item.kind === 'page') {
      return (
        <PageEntry
          key={item.entry.id}
          entry={item.entry}
          level={level}
          workspace={workspace}
          onPageClick={onPageClick}
          onDraftPageClick={onDraftPageClick}
          rowActions={rowActions}
          resolveWikiLink={resolveWikiLink}
          resolveTag={resolveTag}
          resolveEmbed={resolveEmbed}
        />
      );
    }
    return (
      <ResourceRow
        key={item.resource.id}
        resource={item.resource}
        level={level}
        onResourceClick={onResourceClick}
        rowActions={rowActions}
      />
    );
  };

  // A nested level shows its new-folder row just before its first visible subfolder (or after the
  // last item when none is visible), wherever Kind has put the groups.
  const firstFolderIndex = visibleItems.findIndex((item) => item.kind === 'folder');

  const newFolderRow = isCreatingHere && (
    <NewFolderRow
      level={level}
      onCommit={(name) => onCommitNewFolder(name, parentId)}
      onCancel={onCancelNewFolder}
    />
  );

  return (
    <>
      {/* The root opens with the new-folder row; a nested level shows it after its notes and files,
          just before its subfolders. */}
      {parentId === null && newFolderRow}
      {visibleItems.map((item, index) => (
        <Fragment key={item.kind === 'folder' ? item.folder.id : item.kind === 'page' ? item.entry.id : item.resource.id}>
          {parentId !== null && index === firstFolderIndex && newFolderRow}
          {renderItem(item)}
        </Fragment>
      ))}
      {parentId !== null && firstFolderIndex === -1 && newFolderRow}
      {items.length > SIDEBAR_FOLDER_ITEM_LIMIT && (
        <ShowMoreEntry
          level={level}
          hiddenCount={items.length - SIDEBAR_FOLDER_ITEM_LIMIT}
          isExpanded={isCapExpanded}
          onToggle={() => onToggleFolderCap?.(capKey)}
        />
      )}
    </>
  );
}
